In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import chart_studio.plotly as py

from plotly.offline import plot, iplot, init_notebook_mode
# Make plotly work with Jupyter notebook
init_notebook_mode(connected=True)

pd.set_option('display.max_columns', None)


In [2]:
#!pip install pybaseball

In [3]:
from pybaseball import pitching_stats, schedule_and_record, retrosheet
data = pitching_stats(1991, 1992)

In [4]:
data[data.Name == 'Dennis Martinez']

Season             Name   Team   Age     W     L   ERA  WAR     G    GS  \
91   1991.0  Dennis Martinez  Expos  36.0  14.0  11.0  2.39  4.2  31.0  31.0   
106  1992.0  Dennis Martinez  Expos  37.0  16.0  11.0  2.47  3.8  32.0  32.0   

      CG  ShO   SV  BS     IP    TBF      H     R    ER    HR    BB  IBB  HBP  \
91   9.0  5.0  0.0 NaN  222.0  905.0  187.0  70.0  59.0   9.0  62.0  3.0  4.0   
106  6.0  0.0  0.0 NaN  226.1  900.0  172.0  75.0  62.0  12.0  60.0  3.0  9.0   

      WP   BK     SO  GB  FB  LD  IFFB  Balls  Strikes  Pitches  RS  IFH  BU  \
91   3.0  0.0  123.0 NaN NaN NaN   NaN    NaN      NaN      NaN NaN  NaN NaN   
106  2.0  0.0  147.0 NaN NaN NaN   NaN    NaN      NaN      NaN NaN  NaN NaN   

     BUH   K/9  BB/9  K/BB   H/9  HR/9    AVG  WHIP  BABIP   LOB%   FIP  \
91   NaN  4.99  2.51  1.98  7.58  0.36  0.223  1.12  0.252  0.761  3.17   
106  NaN  5.85  2.39  2.45  6.84  0.48  0.207  1.03  0.238  0.740  3.09   

     GB/FB  LD%  GB%  IFFB%  HR/FB  IFH%  BUH%  Starting  Start-IP  Relieving  \
91     NaN  NaN  NaN    NaN    NaN   NaN   NaN      37.5     222.0        NaN   
106    NaN  NaN  NaN    NaN    NaN   NaN   NaN      33.0     226.1        NaN   

     Relief-IP   RAR  Dollars  tERA  xFIP   WPA   -WPA   +WPA   RE24   REW  \
91         NaN  37.5      NaN   NaN   NaN  2.94 -14.04  16.98  22.51  2.53   
106        NaN  33.0      NaN   NaN   NaN  3.04 -13.56  16.60  22.14  2.33   

      pLI  inLI  gmLI  exLI  Pulls  WPA/LI  Clutch  FB%  FBv  SL%  SLv  CT%  \
91   1.06  0.96  0.87  1.07   22.0    2.20    0.58  NaN  NaN  NaN  NaN  NaN   
106  1.02  0.95  0.87  1.31   26.0    3.92   -0.95  NaN  NaN  NaN  NaN  NaN   

     CTv  CB%  CBv  CH%  CHv  SF%  SFv  KN%  KNv  XX%  PO%  wFB  wSL  wCT  \
91   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
106  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

     wCB  wCH  wSF  wKN  wFB/C  wSL/C  wCT/C  wCB/C  wCH/C  wSF/C  wKN/C  \
91   NaN  NaN  NaN  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
106  NaN  NaN  NaN  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

     O-Swing%  Z-Swing%  Swing%  O-Contact%  Z-Contact%  Contact%  Zone%  \
91        NaN       NaN     NaN         NaN         NaN       NaN    NaN   
106       NaN       NaN     NaN         NaN         NaN       NaN    NaN   

     F-Strike%  SwStr%  HLD   SD   MD  ERA-  FIP-  xFIP-     K%    BB%  SIERA  \
91         NaN     NaN  NaN  0.0  0.0  66.0  86.0    NaN  0.136  0.069    NaN   
106        NaN     NaN  NaN  0.0  0.0  71.0  90.0    NaN  0.163  0.067    NaN   

     RS/9   E-F  FA% (pfx)  FT% (pfx)  FC% (pfx)  FS% (pfx)  FO% (pfx)  \
91    NaN -0.77        NaN        NaN        NaN        NaN        NaN   
106   NaN -0.62        NaN        NaN        NaN        NaN        NaN   

     SI% (pfx)  SL% (pfx)  CU% (pfx)  KC% (pfx)  EP% (pfx)  CH% (pfx)  \
91         NaN        NaN        NaN        NaN        NaN        NaN   
106        NaN        NaN        NaN        NaN        NaN        NaN   

     SC% (pfx)  KN% (pfx)  UN% (pfx)  vFA (pfx)  vFT (pfx)  vFC (pfx)  \
91         NaN        NaN        NaN        NaN        NaN        NaN   
106        NaN        NaN        NaN        NaN        NaN        NaN   

     vFS (pfx)  vFO (pfx)  vSI (pfx)  vSL (pfx)  vCU (pfx)  vKC (pfx)  \
91         NaN        NaN        NaN        NaN        NaN        NaN   
106        NaN        NaN        NaN        NaN        NaN        NaN   

     vEP (pfx)  vCH (pfx)  vSC (pfx)  vKN (pfx)  FA-X (pfx)  FT-X (pfx)  \
91         NaN        NaN        NaN        NaN         NaN         NaN   
106        NaN        NaN        NaN        NaN         NaN         NaN   

     FC-X (pfx)  FS-X (pfx)  FO-X (pfx)  SI-X (pfx)  SL-X (pfx)  CU-X (pfx)  \
91          NaN         NaN         NaN         NaN         NaN         NaN   
106         NaN         NaN         NaN         NaN         NaN         NaN   

     KC-X (pfx)  EP-X (pfx)  CH-X (pfx)  SC-X (pfx)  KN

In [5]:
data = schedule_and_record(1991, 'MON')
data.head()

Date   Tm Home_Away  Opp W/L    R   RA   Inn  W-L  Rank    GB  \
1      Monday, Apr 8  MON         @  PIT   W  7.0  0.0   9.0  1-0   1.0  Tied   
2     Tuesday, Apr 9  MON         @  PIT   L  3.0  4.0   9.0  1-1   3.0   1.0   
3  Wednesday, Apr 10  MON         @  PIT   L  3.0  6.0   9.0  1-2   5.0   1.0   
4   Thursday, Apr 11  MON         @  NYM   L  3.0  6.0   9.0  1-3   6.0   2.0   
5     Friday, Apr 12  MON         @  NYM   W  4.0  3.0  11.0  2-3   5.0   1.5   

          Win    Loss     Save  Time D/N  Attendance  Streak Orig. Scheduled  
1    Martinez  Drabek     None  2:51   N     54274.0       1            None  
2      Kipper    Frey  Landrum  2:51   N      6624.0      -1            None  
3       Smith    Boyd  Belinda  2:38   D      7656.0      -2            None  
4  Whitehurst  Mahler   Franco  3:04   N     17271.0      -3            None  
5       Burke  Franco     Frey  3:57   N     22163.0       1            None

In [6]:
data = retrosheet.season_game_logs(1991)
montreal_expos_1991 = data[(data.visiting_team=='MON') | (data.home_team=='MON')]
dennis_martinez_game_logs_1991 = montreal_expos_1991[(montreal_expos_1991.visiting_starting_pitcher_id == 'martd001') |
                                                     (montreal_expos_1991.home_starting_pitcher_id == 'martd001')]
dennis_martinez_game_logs_1991.head()

date  game_num day_of_week visiting_team visiting_team_league  \
7    19910408         0         Mon           MON                   NL   
61   19910413         0         Sat           MON                   NL   
124  19910419         0         Fri           NYN                   NL   
184  19910424         0         Wed           PIT                   NL   
247  19910430         0         Tue           LAN                   NL   

     visiting_game_num home_team home_team_league  home_team_game_num  \
7                    1       PIT               NL                   1   
61                   6       NYN               NL                   6   
124                 11       MON               NL                  11   
184                 15       MON               NL                  15   
247                 20       MON               NL                  20   

     visiting_score  home_score  num_outs day_night  completion_info  \
7                 7           0        54         N              NaN   
61                3           5        51         D              NaN   
124               1           2        51         N              NaN   
184               2           1        54         N              NaN   
247               0           1        51         N              NaN   

     forfeit_info protest_info park_id  attendance  time_of_game_minutes  \
7             NaN          NaN   PIT07     54274.0                 171.0   
61            NaN          NaN   NYC17     26046.0                 204.0   
124           NaN          NaN   MON02     13986.0                 135.0   
184           NaN          NaN   MON02      8592.0                 180.0   
247           NaN          NaN   MON02     10333.0                 131.0   

    visiting_line_score home_line_score  visiting_abs  visiting_hits  \
7             110022100       000000000            40             15   
61            110000001       10200200x            32              7   
124           000000010       20000000x            31              5   
184           100100000       100000000            32              8   
247           000000000       000000001            32              4   

     visiting_doubles  visiting_triples  visiting_homeruns  visiting_rbi  \
7                   2                 0                  2             6   
61                  2                 0                  0             3   
124                 2                 0                  0             1   
184                 2                 0                  0             2   
247                 0                 0                  0             0   

     visiting_sac_hits  visiting_sac_flies  visiting_hbp  visiting_bb  \
7                    0                   0             0            1   
61                   0                   1             0            3   
124                  1                   0             0            0   
184                  1                   0             0            2   
247                  0                   0             0            1   

     visiting_iw  visiting_k  visiting_sb  visiting_cs  visiting_gdp  \
7              0           4            1            0             1   
61             0          14            2            1             0   
124            0           2            1            0             0   
184            0           4            1            0             2   
247            0           7            2            0             0   

     visiting_ci  visiting_lob  visiting_pitchers_used  \
7              0             7                       3   
61             0             6                       3   
124            0             4                       2   
184            0             6                       3   
247            0             6                       1   

     visiting_individual_er  visiting_er  visiting__wp  visiting_balks  \
7                         0            0          

In [7]:
dennis_martinez_game_logs_1991.head()

date  game_num day_of_week visiting_team visiting_team_league  \
7    19910408         0         Mon           MON                   NL   
61   19910413         0         Sat           MON                   NL   
124  19910419         0         Fri           NYN                   NL   
184  19910424         0         Wed           PIT                   NL   
247  19910430         0         Tue           LAN                   NL   

     visiting_game_num home_team home_team_league  home_team_game_num  \
7                    1       PIT               NL                   1   
61                   6       NYN               NL                   6   
124                 11       MON               NL                  11   
184                 15       MON               NL                  15   
247                 20       MON               NL                  20   

     visiting_score  home_score  num_outs day_night  completion_info  \
7                 7           0        54         N              NaN   
61                3           5        51         D              NaN   
124               1           2        51         N              NaN   
184               2           1        54         N              NaN   
247               0           1        51         N              NaN   

     forfeit_info protest_info park_id  attendance  time_of_game_minutes  \
7             NaN          NaN   PIT07     54274.0                 171.0   
61            NaN          NaN   NYC17     26046.0                 204.0   
124           NaN          NaN   MON02     13986.0                 135.0   
184           NaN          NaN   MON02      8592.0                 180.0   
247           NaN          NaN   MON02     10333.0                 131.0   

    visiting_line_score home_line_score  visiting_abs  visiting_hits  \
7             110022100       000000000            40             15   
61            110000001       10200200x            32              7   
124           000000010       20000000x            31              5   
184           100100000       100000000            32              8   
247           000000000       000000001            32              4   

     visiting_doubles  visiting_triples  visiting_homeruns  visiting_rbi  \
7                   2                 0                  2             6   
61                  2                 0                  0             3   
124                 2                 0                  0             1   
184                 2                 0                  0             2   
247                 0                 0                  0             0   

     visiting_sac_hits  visiting_sac_flies  visiting_hbp  visiting_bb  \
7                    0                   0             0            1   
61                   0                   1             0            3   
124                  1                   0             0            0   
184                  1                   0             0            2   
247                  0                   0             0            1   

     visiting_iw  visiting_k  visiting_sb  visiting_cs  visiting_gdp  \
7              0           4            1            0             1   
61             0          14            2            1             0   
124            0           2            1            0             0   
184            0           4            1            0             2   
247            0           7            2            0             0   

     visiting_ci  visiting_lob  visiting_pitchers_used  \
7              0             7                       3   
61             0             6                       3   
124            0             4                       2   
184            0             6                       3   
247            0             6                       1   

     visiting_individual_er  visiting_er  visiting__wp  visiting_balks  \
7                         0            0          

In [8]:
# get datasets
pitching_dataset = pd.read_csv('baseballdatabank-master/core/Pitching.csv')
hof_dataset_results = pd.read_csv('baseballdatabank-master/core/HallOfFame.csv')
awards_results = pd.read_csv('baseballdatabank-master/core/AwardsPlayers.csv')
all_star_results = pd.read_csv('baseballdatabank-master/core/AllstarFull.csv')

In [9]:
pitching_dataset['IP'] = pitching_dataset['IPouts']/3
pitching_dataset.head()

playerID  yearID  stint teamID lgID   W   L   G  GS  CG  SHO  SV  IPouts  \
0  bechtge01    1871      1    PH1  NaN   1   2   3   3   2    0   0      78   
1  brainas01    1871      1    WS3  NaN  12  15  30  30  30    0   0     792   
2  fergubo01    1871      1    NY2  NaN   0   0   1   0   0    0   0       3   
3  fishech01    1871      1    RC1  NaN   4  16  24  24  22    1   0     639   
4  fleetfr01    1871      1    NY2  NaN   0   1   1   1   1    0   0      27   

     H   ER  HR  BB  SO  BAOpp    ERA  IBB  WP  HBP  BK     BFP  GF    R  SH  \
0   43   23   0  11   1    NaN   7.96  NaN   7  NaN   0   146.0   0   42 NaN   
1  361  132   4  37  13    NaN   4.50  NaN   7  NaN   0  1291.0   0  292 NaN   
2    8    3   0   0   0    NaN  27.00  NaN   2  NaN   0    14.0   0    9 NaN   
3  295  103   3  31  15    NaN   4.35  NaN  20  NaN   0  1080.0   1  257 NaN   
4   20   10   0   3   0    NaN  10.00  NaN   0  NaN   0    57.0   0   21 NaN   

   SF  GIDP     IP  
0 NaN   NaN   26.0  
1 NaN   NaN  264.0  
2 NaN   NaN    1.0  
3 NaN   NaN  213.0  
4 NaN   NaN    9.0

In [10]:
# lets get from 1976 onward, sicne martide01 debut in 1976
awards_results = awards_results[awards_results['yearID'] > 1976]
all_star_results = all_star_results[all_star_results['yearID'] > 1976]
pitching_awards = awards_results[(awards_results['awardID'] == 'Pitching Triple Crown') |
                                 (awards_results['awardID'] == 'Cy Young Award') |
                                 ((awards_results['awardID'] == 'Gold Glove') & (awards_results['notes'] == 'P'))]

In [11]:
# hof dataset
hof_dataset = hof_dataset_results[hof_dataset_results['inducted'] == 'Y']

In [12]:
hof_dataset.head()

playerID  yearID votedBy  ballots  needed  votes inducted category  \
0   cobbty01    1936   BBWAA    226.0   170.0  222.0        Y   Player   
1   ruthba01    1936   BBWAA    226.0   170.0  215.0        Y   Player   
2  wagneho01    1936   BBWAA    226.0   170.0  215.0        Y   Player   
3  mathech01    1936   BBWAA    226.0   170.0  205.0        Y   Player   
4  johnswa01    1936   BBWAA    226.0   170.0  189.0        Y   Player   

  needed_note  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN

## Dennis Martinez stats

In [13]:
dennis_martinez_dataset = pitching_dataset[pitching_dataset['playerID'] == 'martide01']
career_first_year = min(dennis_martinez_dataset['yearID'])
career_last_year = max(dennis_martinez_dataset['yearID'])

In [14]:
dennis_martinez_dataset.describe()

yearID      stint          W          L          G         GS  \
count    24.000000  24.000000  24.000000  24.000000  24.000000  24.000000   
mean   1986.958333   1.041667  10.208333   8.041667  28.833333  23.416667   
std       6.636390   0.204124   5.397094   4.133418  11.801498  11.776604   
min    1976.000000   1.000000   0.000000   0.000000   4.000000   0.000000   
25%    1981.750000   1.000000   6.000000   5.000000  23.500000  14.500000   
50%    1986.500000   1.000000  11.500000   7.000000  32.000000  24.500000   
75%    1992.250000   1.000000  15.000000  11.000000  34.250000  32.250000   
max    1998.000000   2.000000  16.000000  16.000000  53.000000  39.000000   

              CG        SHO         SV      IPouts           H          ER  \
count  24.000000  24.000000  24.000000   24.000000   24.000000   24.000000   
mean    5.083333   1.250000   0.333333  499.958333  162.375000   68.458333   
std     4.708149   1.293798   0.916831  231.039895   69.763459   29.479513   
min     0.000000   0.000000   0.000000   20.000000   11.000000    5.000000   
25%     1.750000   0.000000   0.000000  326.750000  118.750000   52.250000   
50%     3.500000   1.000000   0.000000  533.500000  172.500000   67.500000   
75%     7.500000   2.000000   0.000000  678.250000  209.500000   85.000000   
max    18.000000   5.000000   4.000000  877.000000  279.000000  119.000000   

              HR         BB          SO      BAOpp        ERA        IBB  \
count  24.000000  24.000000   24.000000  24.000000  24.000000  24.000000   
mean   15.500000  48.541667   89.541667   0.264708   4.022500   2.958333   
std     8.526175  22.294431   44.120368   0.035887   1.311784   2.255027   
min     0.000000   2.000000    2.000000   0.211000   2.390000   0.000000   
25%     9.750000  37.000000   62.750000   0.245500   3.155000   1.750000   
50%    13.000000  47.500000   90.000000   0.253500   3.755000   2.500000   
75%    21.000000  62.250000  125.250000   0.275000   4.522500   4.000000   
max    30.000000  93.000000  156.000000   0.367000   7.710000   9.000000   

              WP        HBP         BK          BFP         GF           R  \
count  24.000000  24.000000  24.000000    24.000000  24.000000   24.000000   
mean    3.458333   5.083333   1.250000   698.083333   2.125000   76.458333   
std     2.603996   3.361116   2.171956   313.834894   4.513868   32.478728   
min     0.000000   0.000000   0.000000    33.000000   0.000000    5.000000   
25%     1.750000   2.000000   0.000000   469.250000   0.000000   57.500000   
50%     3.000000   5.500000   0.500000   741.500000   0.000000   77.500000   
75%     5.000000   7.000000   2.000000   917.250000   1.000000   97.500000   
max     9.000000  12.000000  10.000000  1206.000000  19.000000  129.000000   

              SH         SF       GIDP          IP  
count  24.000000  24.000000  24.000000   24.000000  
mean    5.000000   4.541667  13.833333  166.652778  
std     4.191088   2.903958   7.498792   77.013298  
min     0.000000   0.000000   0.000000    6.666667  
25%     1.750000   3.000000   9.000000  108.916667  
50%     3.500000   4.000000  14.000000  177.833333  
75%     8.000000   5.250000  17.750000  226.083333  
max    12.000000  12.000000  32.000000  292.333333

### Best Years

In 1981, Dennis Martinez was leading the league in wins with 14 and had one of the highest win/loss ratio with a record of 14 wins and 5 losses. The season was cut short due to the strike that occurred, which left Dennis tied with the most wins with Pete Vuckovich in the American League (who was still one game short of Dennis). That year the Cy Young award was granted to Rollie Fingers, which was the first time in MLB history that the Cy Young Award was given to a relief pitcher.

In 1991 and 1992 while playing with the Montreal Expos, Dennis had his lowest ERA of his career at 2.39 and 2.47 with both years having more than 220 innings pitched. In 1991, he had the lowest ERA of any started who had more than 200 innings and in 1992, he finished in the top 10 of lowest ERA with starters throwing more than 200 innings. In additiuon to highest ERA, he also contained an impressive record even though having an average of 3.5 for run support for games started, in comparison to Tom Glavine's 4.67 (whom went on to win the Cy Young with a record of 20-11)

In [15]:
# number of wins with standard deviation of 5
max_num_wins = max(dennis_martinez_dataset.W)
std_dev_wins = dennis_martinez_dataset.W.std()
most_wins_years = dennis_martinez_dataset[
    dennis_martinez_dataset.W >= max_num_wins - std_dev_wins].sort_values(by=['W'], ascending=False)


best_era_years = dennis_martinez_dataset[
    dennis_martinez_dataset.ERA <= 
    min(dennis_martinez_dataset.ERA) + dennis_martinez_dataset.ERA.std()].sort_values(by=['ERA'], ascending=True)

In [16]:
best_era_years.head()

playerID  yearID  stint teamID lgID   W   L   G  GS  CG  SHO  SV  \
28111  martide01    1991      1    MON   NL  14  11  31  31   9    5   0   
28581  martide01    1992      1    MON   NL  16  11  32  32   6    0   0   
21619  martide01    1976      1    BAL   AL   1   2   4   2   1    0   0   
26595  martide01    1988      1    MON   NL  15  13  34  34   9    2   0   
27588  martide01    1990      1    MON   NL  10  11  32  32   7    2   0   

       IPouts    H  ER  HR  BB   SO  BAOpp   ERA  IBB  WP  HBP  BK    BFP  GF  \
28111     666  187  59   9  62  123  0.226  2.39  3.0   3  4.0   0  905.0   0   
28581     679  172  62  12  60  147  0.211  2.47  3.0   2  9.0   0  900.0   0   
21619      83   23   8   1   8   18  0.237  2.60  0.0   1  0.0   0  106.0   1   
26595     706  215  71  21  55  120  0.239  2.72  3.0   5  6.0  10  968.0   0   
27588     678  191  74  16  49  156  0.228  2.95  9.0   1  6.0   1  908.0   0   

        R    SH   SF  GIDP          IP  
28111  70   7.0  3.0  14.0  222.000000  
28581  75  12.0  5.0   9.0  226.333333  
21619   8   1.0  0.0   3.0   27.666667  
26595  94   2.0  6.0  17.0  235.333333  
27588  80  11.0  3.0  13.0  226.000000

In [17]:
## lets find what the league average was for those time periods
# Year of the strike
pitching_1991 = pitching_dataset[pitching_dataset.yearID == 1991]

pitching_1991[(pitching_1991.ERA <= min(dennis_martinez_dataset.ERA) + dennis_martinez_dataset.ERA.std()) 
              & (pitching_1991.IP > 200)].sort_values(by=['ERA'], ascending=True).head()

playerID  yearID  stint teamID lgID   W   L   G  GS  CG  SHO  SV  \
28111  martide01    1991      1    MON   NL  14  11  31  31   9    5   0   
28203   rijojo01    1991      1    CIN   NL  15   6  30  30   3    1   0   
27980  glavito02    1991      1    ATL   NL  20  11  34  34   9    1   0   
27848  belchti01    1991      1    LAN   NL  10   9  33  33   2    1   0   
27908  clemero02    1991      1    BOS   AL  18  10  35  35  13    4   0   

       IPouts    H  ER  HR  BB   SO  BAOpp   ERA   IBB  WP  HBP  BK     BFP  \
28111     666  187  59   9  62  123  0.226  2.39   3.0   3  4.0   0   905.0   
28203     613  165  57   8  55  172  0.219  2.51   4.0   2  3.0   4   825.0   
27980     740  201  70  17  69  192  0.222  2.55   6.0  10  2.0   2   989.0   
27848     628  189  61  10  75  156  0.240  2.62   3.0   7  2.0   0   880.0   
27908     814  219  79  15  65  241  0.221  2.62  12.0   6  5.0   0  1077.0   

       GF   R    SH   SF  GIDP          IP  
28111   0  70   7.0  3.0  14.0  222.000000  
28203   0  69   4.0  8.0  15.0  204.333333  
27980   0  83   7.0  6.0  19.0  246.666667  
27848   0  76  11.0  3.0  15.0  209.333333  
27908   0  93   6.0  8.0  17.0  271.333333

In [18]:
## lets find what the league average was for those time periods
# Year of the strike
pitching_1992 = pitching_dataset[pitching_dataset.yearID == 1992]

pitching_1992[(pitching_1992.ERA <= min(dennis_martinez_dataset.ERA) + dennis_martinez_dataset.ERA.std()) 
              & (pitching_1992.IP > 200)].sort_values(by=['ERA'], ascending=True).head(10)

playerID  yearID  stint teamID lgID   W   L   G  GS  CG  SHO  SV  \
28742  tewksbo01    1992      1    SLN   NL  16   5  33  32   5    0   0   
28574  maddugr01    1992      1    CHN   NL  20  11  35  35   9    4   0   
28705  schilcu01    1992      1    PHI   NL  14  11  42  26  10    4   2   
28400  clemero02    1992      1    BOS   AL  18  11  32  32  11    5   0   
28324  appieke01    1992      1    KCA   AL  15   8  30  30   3    0   0   
28581  martide01    1992      1    MON   NL  16  11  32  32   6    0   0   
28616  mussimi01    1992      1    BAL   AL  18   5  32  32   8    4   0   
28611  morgami01    1992      1    CHN   NL  16   8  34  34   6    1   0   
28675   rijojo01    1992      1    CIN   NL  15  10  33  33   2    0   0   
28518   hillke01    1992      1    MON   NL  16   9  33  33   3    3   0   

       IPouts    H  ER  HR  BB   SO  BAOpp   ERA   IBB  WP   HBP  BK     BFP  \
28742     699  217  56  15  20   91  0.248  2.16   0.0   2   3.0   0   915.0   
28574     804  201  65   7  70  199  0.210  2.18   7.0   5  14.0   0  1061.0   
28705     679  165  59  11  59  147  0.201  2.35   4.0   4   1.0   0   895.0   
28400     740  203  66  11  62  208  0.224  2.41   5.0   3   9.0   0   989.0   
28324     625  167  57  10  68  150  0.217  2.46   5.0   4   2.0   0   852.0   
28581     679  172  62  12  60  147  0.211  2.47   3.0   2   9.0   0   900.0   
28616     723  212  68  16  48  130  0.239  2.54   2.0   6   2.0   0   957.0   
28611     720  203  68  14  79  123  0.234  2.55  10.0  11   3.0   0   966.0   
28675     633  185  60  15  44  171  0.238  2.56   1.0   2   3.0   1   836.0   
28518     654  187  65  13  75  150  0.230  2.68   4.0  11   3.0   4   908.0   

       GF   R    SH   SF  GIDP          IP  
28742   1  63   9.0  7.0  25.0  233.000000  
28574   0  68  15.0  3.0  19.0  268.000000  
28705  10  67   7.0  8.0  11.0  226.333333  
28400   0  80   5.0  5.0  28.0  246.666667  
28324   0  59   8.0  3.0  12.0  208.333333  
28581   0  75  12.0  5.0   9.0  226.333333  
28616   0  70  13.0  6.0  18.0  241.000000  
28611   0  80  10.0  5.0  29.0  240.000000  
28675   0  67   9.0  4.0  16.0  211.000000  
28518   0  76  15.0  3.0  12.0  218.000000

In [19]:
# best win to loss ratio
# win_loss_ratio 
most_wins_years['win_loss_ratio'] = most_wins_years.W/most_wins_years.L
most_wins_years = most_wins_years.sort_values(by=['win_loss_ratio'], ascending=False)
most_wins_years.head()

playerID  yearID  stint teamID lgID   W  L   G  GS  CG  SHO  SV  \
23587  martide01    1981      1    BAL   AL  14  5  25  24   9    2   0   
26138  martide01    1987      1    MON   NL  11  4  22  22   2    1   0   
30170  martide01    1995      1    CLE   AL  12  5  28  28   3    2   0   
27079  martide01    1989      1    MON   NL  16  7  34  33   5    2   0   
21999  martide01    1977      1    BAL   AL  14  7  42  13   5    0   4   

       IPouts    H  ER  HR  BB   SO  BAOpp   ERA  IBB  WP   HBP  BK    BFP  \
23587     537  173  66  10  62   88  0.254  3.32  1.0   6   2.0   1  753.0   
26138     434  133  53   9  40   84  0.244  3.30  2.0   4   6.0   2  599.0   
30170     561  174  64  17  46   99  0.247  3.08  2.0   3  12.0   0  771.0   
27079     696  227  82  21  49  142  0.257  3.18  4.0   5   7.0   2  950.0   
21999     500  157  76  10  64  107  0.253  4.10  5.0   5   8.0   0  709.0   

       GF   R   SH   SF  GIDP          IP  win_loss_ratio  
23587   0  84  2.0  5.0  14.0  179.000000        2.800000  
26138   0  59  4.0  3.0   8.0  144.666667        2.750000  
30170   0  71  4.0  4.0  14.0  187.000000        2.400000  
27079   1  88  8.0  2.0  21.0  232.000000        2.285714  
21999  19  86  8.0  8.0  20.0  166.666667        2.000000

In [20]:
## lets find what the league average was for those time periods
# Year of the strike
pitching_1981 = pitching_dataset[pitching_dataset.yearID == 1981]

pitching_1981[(pitching_1981.W/pitching_1981.L > 2) 
              & (pitching_1981.W > 10)].sort_values(by=['W'], ascending=False).head()

playerID  yearID  stint teamID lgID   W  L   G  GS  CG  SHO  SV  \
23587  martide01    1981      1    BAL   AL  14  5  25  24   9    2   0   
23689  seaveto01    1981      1    CIN   NL  14  2  23  23   6    1   0   
23736  vuckope01    1981      1    ML4   AL  14  4  24  23   2    1   0   
23439  carltst01    1981      1    PHI   NL  13  4  24  24  10    1   0   
23602  mcgresc01    1981      1    BAL   AL  13  5  24  22   8    3   0   

       IPouts    H  ER  HR  BB   SO  BAOpp   ERA  IBB  WP  HBP  BK    BFP  GF  \
23587     537  173  66  10  62   88  0.254  3.32  1.0   6  2.0   1  753.0   0   
23689     499  120  47  10  66   87  0.205  2.54  8.0   5  3.0   0  671.0   0   
23736     449  137  59   9  57   84  0.249  3.55  1.0   1  4.0   0  620.0   0   
23439     570  152  51   9  62  179  0.222  2.42  3.0   9  1.0   4  763.0   0   
23602     480  167  58  13  40   82  0.273  3.26  5.0   3  0.0   1  664.0   2   

        R    SH   SF  GIDP          IP  
23587  84   2.0  5.0  14.0  179.000000  
23689  51   9.0  8.0  13.0  166.333333  
23736  61   7.0  1.0  16.0  149.666667  
23439  59  12.0  4.0  13.0  190.000000  
23602  63   7.0  6.0  20.0  160.000000

In [21]:
## lets find what the league average was for those time periods
# Year of the strike
pitching_1981 = pitching_dataset[pitching_dataset.yearID == 1981]

pitching_1981[(pitching_1981.W/pitching_1981.L > 2) 
              & (pitching_1981.W > 10) 
              & (pitching_1981.lgID == 'AL')].sort_values(by=['W'], ascending=False).head()

playerID  yearID  stint teamID lgID   W  L   G  GS  CG  SHO  SV  \
23587  martide01    1981      1    BAL   AL  14  5  25  24   9    2   0   
23736  vuckope01    1981      1    ML4   AL  14  4  24  23   2    1   0   
23602  mcgresc01    1981      1    BAL   AL  13  5  24  22   8    3   0   
23504  guidrro01    1981      1    NYA   AL  11  5  23  21   0    0   0   

       IPouts    H  ER  HR  BB   SO  BAOpp   ERA  IBB  WP  HBP  BK    BFP  GF  \
23587     537  173  66  10  62   88  0.254  3.32  1.0   6  2.0   1  753.0   0   
23736     449  137  59   9  57   84  0.249  3.55  1.0   1  4.0   0  620.0   0   
23602     480  167  58  13  40   82  0.273  3.26  5.0   3  0.0   1  664.0   2   
23504     381  100  39  12  26  104  0.214  2.76  0.0   6  1.0   0  497.0   1   

        R   SH   SF  GIDP          IP  
23587  84  2.0  5.0  14.0  179.000000  
23736  61  7.0  1.0  16.0  149.666667  
23602  63  7.0  6.0  20.0  160.000000  
23504  41  1.0  1.0   8.0  127.000000

In [22]:
pitching_1981[pitching_1981.playerID == 'fingero01']

playerID  yearID  stint teamID lgID  W  L   G  GS  CG  SHO  SV  \
23479  fingero01    1981      1    ML4   AL  6  3  47   0   0    0  28   

       IPouts   H  ER  HR  BB  SO  BAOpp   ERA  IBB  WP  HBP  BK    BFP  GF  \
23479     234  55   9   3  13  61  0.198  1.04  5.0   1  1.0   0  297.0  41   

       R   SH   SF  GIDP    IP  
23479  9  4.0  1.0   8.0  78.0

In [23]:
pitching_awards[pitching_awards.yearID == 1989].head()

playerID         awardID  yearID lgID  tie notes
4086  saberbr01  Cy Young Award    1989   AL  NaN   NaN
4087  davisma01  Cy Young Award    1989   NL  NaN   NaN
4095  saberbr01      Gold Glove    1989   AL  NaN     P
4104  darliro01      Gold Glove    1989   NL  NaN     P

In [24]:
dennis_martinez_run_support = pd.read_csv('dennis_martinez_rs.csv').fillna(0)
dennis_martinez_run_support.head()

Year   Avg    0    1    2     3    4    5    6    7    8    9  \
0  1976  1.50  1.0  0.0  0.0   1.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  1977  5.91  1.0  0.0  1.0   0.0  2.0  4.0  0.0  2.0  0.0  0.0   
2  1978  4.62  2.0  4.0  1.0  11.0  2.0  4.0  6.0  2.0  2.0  1.0   
3  1979  3.95  2.0  5.0  3.0   9.0  4.0  7.0  5.0  1.0  1.0  0.0   
4  1980  4.38  0.0  3.0  2.0   0.0  0.0  3.0  1.0  1.0  0.0  2.0   

   Other Game Totals  
0                  0  
1  10 11 and 12 runs  
2  10 10 and 11 runs  
3     10 and 10 runs  
4                  0

In [25]:
dennis_martinez_run_support.Avg.mean()

4.586956521739131

In [26]:
dennis_martinez_run_support[
    (dennis_martinez_run_support.Year >=1986) & 
    (dennis_martinez_run_support.Year <= 1993)].Avg.mean()

4.116250000000001

In [27]:
game_logs_1991 = pd.read_csv('1991_game_logs.csv')
game_logs_1991.head()

Rk   Gcar   Gtm    Date   Tm Unnamed: 5  Opp  Rslt Inngs     Dec    DR  \
0  1.0  461.0   1.0   Apr 8  MON          @  PIT  W7-0  GS-7  W(1-0)  99.0   
1  2.0  462.0   6.0  Apr 13  MON          @  NYM  L3-5  GS-5  L(1-1)   4.0   
2  3.0  463.0  11.0  Apr 19  MON        NaN  NYM  W2-1  GS-8  W(2-1)   5.0   
3  4.0  464.0  15.0  Apr 24  MON        NaN  PIT  L1-2  GS-8  L(2-2)   4.0   
4  5.0  465.0  20.0  Apr 30  MON        NaN  LAD  W1-0   SHO  W(3-2)   5.0   

    IP  H  R  ER  BB  SO  HR  HBP   ERA  BF  Pit Str StL StS    GB    FB LD  \
0  7.0  1  0   0   2   5   0    0  0.00  26  111  62  26   5   7.0  12.0  3   
1  5.0  5  3   2   6   6   0    1  1.50  28  136  76  27  13   6.0   9.0  8   
2  7.2  5  1   1   0   2   0    0  1.37  28  101  67  14   5  15.0  11.0  4   
3  8.0  8  2   2   2   3   0    0  1.63  32  112  76  17   8  14.0  13.0  6   
4  9.0  4  0   0   1   7   0    0  1.23  33  111  72  25   8  19.0   6.0  3   

  PU  Unk  GSc  IR   IS  SB  CS  PO  AB  2B  3B  IBB  GDP  SF  ROE   aLI  \
0  0    0   78 NaN  NaN   1   0   0  24   0   0    0    0   0    2  0.74   
1  0    0   47 NaN  NaN   2   0   0  20   2   0    0    0   1    0  1.54   
2  1    0   67 NaN  NaN   0   0   1  27   2   0    0    0   0    1  1.02   
3  2    0   59 NaN  NaN   1   0   0  29   2   0    0    2   0    0  1.22   
4  1    0   85 NaN  NaN   2   0   0  32   0   0    0    0   0    1  1.37   

     WPA  RE24       Entered           Exited  
0  0.262  3.17  1b start a 1      7b 3 out a7  
1 -0.134 -0.74  1b start a 1      5b 3 out d1  
2  0.322  2.41  1t start tie  8t 1-- 2 out a1  
3  0.147  1.62  1t start tie      8t 3 out d1  
4  0.654  4.08  1t start tie     9t 3 out tie

In [28]:
# data per team
# baltimore orioles
orioles = dennis_martinez_dataset[dennis_martinez_dataset['teamID'] == 'BAL']
# montreal expos
expos = dennis_martinez_dataset[dennis_martinez_dataset['teamID'] == 'MON']
# cleveland indians
indians = dennis_martinez_dataset[dennis_martinez_dataset['teamID'] == 'CLE']
# seattle mariners
mariners = dennis_martinez_dataset[dennis_martinez_dataset['teamID'] == 'SEA']
# atlanta braves
braves = dennis_martinez_dataset[dennis_martinez_dataset['teamID'] == 'ATL']

In [29]:
# expos can be considered prime years
# lets get montreal expos years
first_yr_expos = min(expos['yearID'])
last_yr_expos = max(expos['yearID'])

In [30]:
# get all pitching data from montreal expos years
all_pitching_data = pitching_dataset[(pitching_dataset['yearID'] >= first_yr_expos) & 
                                     (pitching_dataset['yearID'] <= last_yr_expos) &
                                     (pitching_dataset['playerID'] != 'martide01')
                                    ]

In [31]:
# d martinez was a starter so lets compare with starters
hof_pitching_data = pd.merge(all_pitching_data, hof_dataset, how="inner", on="playerID")
hof_pitching_starters = hof_pitching_data[hof_pitching_data['GS'] > 5]

In [32]:
stat_columns = expos.columns
hof_pitching_starters = hof_pitching_starters.iloc[:,0:-8]

In [33]:
combined_stats = hof_pitching_starters.append(expos)
unique_player_ids = combined_stats.playerID.unique()
combined_stats['yearID'] = combined_stats[['yearID','yearID_x']].max(axis=1)
combined_stats = combined_stats.drop(['yearID_x'], axis=1)

In [34]:
fig = go.Figure()

for player_id in unique_player_ids:
    stats = combined_stats[combined_stats.playerID == player_id]
    linewidth = 1.0
    if player_id == 'martide01':
        linewidth = 5.0
    fig.add_trace(go.Scatter(
        x=stats.yearID,
        y=stats.W,
        name=player_id,
        mode="lines+markers",
        line=dict(width=linewidth)
    ))

fig.update_layout(title="Number of Wins per Year", xaxis_title="# of Wins", yaxis_title="Year")
fig.show()

In [35]:
fig = go.Figure()

for player_id in unique_player_ids:
    stats = combined_stats[combined_stats.playerID == player_id]
    linewidth = 1.0
    if player_id == 'martide01':
        linewidth = 5.0
    fig.add_trace(go.Scatter(
        x=stats.yearID,
        y=np.log(stats.W),
        name=player_id,
        mode="lines+markers",
        line=dict(width=linewidth)
    ))
fig.update_layout(title="Logged Number of Wins per Year", xaxis_title="# of Wins", yaxis_title="Year")
fig.show()


/Users/rmartinez/.pyenv/versions/3.8.1/envs/jupyter_notebook_3.8/lib/python3.8/site-packages/pandas/core/series.py:679: RuntimeWarning:

divide by zero encountered in log



In [36]:
fig = go.Figure()

for player_id in unique_player_ids:
    stats = combined_stats[combined_stats.playerID == player_id]
    linewidth = 1.0
    if player_id == 'martide01':
        linewidth = 5.0
    fig.add_trace(go.Scatter(
        x=stats.yearID,
        y=(stats.IPouts/3),
        name=player_id,
        mode="lines+markers",
        line=dict(width=linewidth)
    ))
    
fig.update_layout(title="Innings Pitched", xaxis_title="Year", yaxis_title="# of Innings")
fig.show()


In [37]:
summed_stats = combined_stats.groupby(['playerID']).sum()

In [38]:
fig = go.Figure(data=[
    go.Bar(x=summed_stats.index, 
           y=(summed_stats['IPouts']/3).as_matrix(),
           text=list(round(summed_stats['IPouts']/3,2)),
           textposition="auto"
          )
])

fig.update_layout(title="Total Innings Pitched from 1986 - 1993", xaxis_title="Year", yaxis_title="# of Innings")
fig.show()

AttributeError: 'Series' object has no attribute 'as_matrix'

In [39]:
# get season data
# season_1981 = pd.read_csv('GL1981.TXT', header=None)
# season_1991 = pd.read_csv('GL1991.TXT', header=None)
season_1994 = pd.read_csv('gamelogs/GL1994.TXT', header=None)

In [40]:
season_1994.head(15)

0    1    2    3   4    5    6   7    8    9    10   11  12   13   \
0   19940403    0  Sun  SLN  NL    1  CIN  NL    1    6    4   54   N  NaN   
1   19940404    0  Mon  KCA  AL    1  BAL  AL    1    3    6   51   D  NaN   
2   19940404    0  Mon  DET  AL    1  BOS  AL    1    8    9   51   D  NaN   
3   19940404    0  Mon  SEA  AL    1  CLE  AL    1    3    4   65   D  NaN   
4   19940404    0  Mon  TEX  AL    1  NYA  AL    1    3    5   51   D  NaN   
5   19940404    0  Mon  CHA  AL    1  TOR  AL    1    3    7   51   D  NaN   
6   19940404    0  Mon  NYN  NL    1  CHN  NL    1   12    8   54   D  NaN   
7   19940404    0  Mon  SLN  NL    2  CIN  NL    2    4    5   58   D  NaN   
8   19940404    0  Mon  PHI  NL    1  COL  NL    1   12    6   54   D  NaN   
9   19940404    0  Mon  MON  NL    1  HOU  NL    1    5    6   71   D  NaN   
10  19940404    0  Mon  ATL  NL    1  SDN  NL    1    4    1   54   D  NaN   
11  19940404    0  Mon  PIT  NL    1  SFN  NL    1    0    8   51   D  NaN   
12  19940405    0  Tue  OAK  AL    1  MIL  AL    1    7   11   51   D  NaN   
13  19940405    0  Tue  CAL  AL    1  MIN  AL    1    8    2   54   N  NaN   
14  19940405    0  Tue  CHA  AL    2  TOR  AL    2    3    5   51   N  NaN   

    14   15     16     17   18            19            20   21   22   23   \
0   NaN  NaN  CIN08  32803  169     102210000     030001000   35   11    2   
1   NaN  NaN  BAL12  47549  168     000100002     10011210x   31    5    0   
2   NaN  NaN  BOS07  34023  213     003140000     01500003x   37   10    4   
3   NaN  NaN  CLE08  41459  209   10100000010   00000002011   38    7    1   
4   NaN  NaN  NYC16  56706  156     000100110     10202000x   34    7    5   
5   NaN  NaN  TOR02  50484  174     001001001     00100033x   35    9    3   
6   NaN  NaN  CHI11  38413  180     002431011     101320001   39   16    4   
7   NaN  NaN  CIN08  55093  227    0000030100    0004000001   41   13    2   
8   NaN  NaN  DEN01  72470  216     002000280     012001200   38    9    1   
9   NaN  NaN  HOU02  43440  237  030000000002  000120000003   40    6    1   
10  NaN  NaN  SAN01  42251  156     010011100     000000001   33    6    2   
11  NaN  NaN  SFO02  58077  150     000000000     01303100x   32    6    2   
12  NaN  NaN  MIL05  52012  207     500001001     11300501x   31    8    2   
13  NaN  NaN  MIN03  41012  167     240110000     010000010   40   15    3   
14  NaN  NaN  TOR02  44471  157     000002010     01000301x   33    6    1   

    24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   \
0     0    1    5    2    0    0    4    1    8    1    1    0    0    8    3   
1     0    1    3    0    0    0    3    0    4    0    0    0    0    4    5   
2     0    0    8    0    0    1    6    2   10    0    1    0    0    9    3   
3     0    1    3    2    1    1    5    0    7    0    0    0    0   11    4   
4     0    0    3    0    1    0    1    0    4    0    0    0    0    6    3   
5     0    1    3    0    0    0    5    0    5    1    0    1    0   10    3   
6     1    3   12    1    2    0    7    1    7    1    0    0    0   10    4   
7     0    0    3    0    0    0    7    0   11    1    1    0    0   14    5   
8     0    1    8    0    0    2   10    0    5    1    0    0    0   11    4   
9     0    1    5    1    0    0    6    0    9    0    1    0    0    6    6   
10    0    2    3    1    0    0    2    0    4    1    0    0    0    5    2   
11    0    0    0    0    0    1    2    0    4    0    0    1    0    8    4   
12    0    2    7    0    2    0    8    0    6    1    1    1    0    7    5   
13    0    0    8    0    0    1    6    0    3    0    0    1    0   12    2   
14    0    1    3    0    0    0    6    1    8    1    0    0    0    9    3   

    39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   \
0     3    3    2    0   27   14    1    0    1    0   33    8    1    0    1   
1     4    4    0    0   24    8    3    0    2    0

In [41]:
all_seasons = pd.read_csv('gamelogs/test.TXT', header=None)

/Users/rmartinez/.pyenv/versions/3.8.1/envs/jupyter_notebook_3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3062: DtypeWarning:

Columns (13,14,15,85,87) have mixed types.Specify dtype option on import or set low_memory=False.



In [42]:
all_seasons.head(20)

0    1    2    3   4    5    6   7    8    9    10   11  12   13   \
0   19760408    0  Thu  NYA  AL    1  MIL  AL    1    0    5   51   D  NaN   
1   19760408    0  Thu  HOU  NL    1  CIN  NL    1    5   11   51   D  NaN   
2   19760409    0  Fri  BOS  AL    1  BAL  AL    1    0    1   51   D  NaN   
3   19760409    0  Fri  OAK  AL    1  CAL  AL    1    5    2   54   N  NaN   
4   19760409    0  Fri  KCA  AL    1  CHA  AL    1    0    4   51   N  NaN   
5   19760409    0  Fri  MIN  AL    1  TEX  AL    1    1    2   65   N  NaN   
6   19760409    0  Fri  MON  NL    1  NYN  NL    1    2    3   51   D  NaN   
7   19760409    0  Fri  ATL  NL    1  SDN  NL    1    2    8   51   N  NaN   
8   19760409    0  Fri  LAN  NL    1  SFN  NL    1    2    4   51   D  NaN   
9   19760409    0  Fri  CHN  NL    1  SLN  NL    1    0    5   51   N  NaN   
10  19760410    0  Sat  BOS  AL    2  BAL  AL    2    1    5   51   D  NaN   
11  19760410    0  Sat  OAK  AL    2  CAL  AL    2    6    2   54   D  NaN   
12  19760410    0  Sat  DET  AL    1  CLE  AL    1    3    1   54   D  NaN   
13  19760410    0  Sat  NYA  AL    2  MIL  AL    2    9    7   54   D  NaN   
14  19760410    0  Sat  MIN  AL    2  TEX  AL    2    1    4   51   N  NaN   
15  19760410    0  Sat  HOU  NL    2  CIN  NL    2    7   13   51   D  NaN   
16  19760410    0  Sat  MON  NL    2  NYN  NL    2    0    1   51   D  NaN   
17  19760410    0  Sat  PIT  NL    1  PHI  NL    1    5    4   66   D  NaN   
18  19760410    0  Sat  ATL  NL    2  SDN  NL    2    3    0   54   N  NaN   
19  19760410    0  Sat  CHN  NL    2  SLN  NL    2    4    3   54   D  NaN   

    14   15     16       17     18           19           20    21    22   \
0   NaN    V  MIL05  44868.0  129.0    000000000    32000000x  30.0   4.0   
1   NaN  NaN  CIN08  52949.0  161.0    000013100    03102500x  36.0  11.0   
2   NaN  NaN  BAL11  46425.0  123.0    000000000    00010000x  31.0   6.0   
3   NaN  NaN  ANA01  30194.0  154.0    100210010    101000000  33.0   9.0   
4   NaN  NaN  CHI10  40318.0  145.0    000000000    00112000x  32.0   6.0   
5   NaN  NaN  ARL01  28947.0  168.0  00000100000  01000000001  38.0   7.0   
6   NaN  NaN  NYC17  17013.0  155.0    001000010    01020000x  35.0   8.0   
7   NaN  NaN  SAN01  44728.0  134.0    000000200    10024001x  30.0   5.0   
8   NaN  NaN  SFO02  37261.0  127.0    100000100    10020100x  33.0   6.0   
9   NaN  NaN  STL09  30761.0  131.0    000000000    00002030x  33.0   6.0   
10  NaN  NaN  BAL11   8899.0  150.0    000000100    00000005x  30.0   8.0   
11  NaN  NaN  ANA01  10143.0  167.0    000020031    000000020  33.0   7.0   
12  NaN  NaN  CLE07  58478.0  153.0    102000000    000000100  32.0   7.0   
13  NaN  NaN  MIL05  10871.0  203.0    000000405    000123001  39.0  13.0   
14  NaN  NaN  ARL01  13005.0  140.0    001000000    01020100x  31.0   6.0   
15  NaN  NaN  CIN08  16728.0  160.0    100102300    53000041x  39.0  13.0   
16  NaN  NaN  NYC17  12035.0  115.0    000000000    00010000x  30.0   4.0   
17  NaN  NaN  PHI12  42147.0  167.0  10001100101  01000003000  42.0  12.0   
18  NaN  NaN  SAN01  17445.0  129.0    000000300    000000000  33.0   4.0   
19  NaN  NaN  STL09  14225.0  131.0    200000200    000020001  33.0   9.0   

    23   24   25   26   27   28   29   30   31    32   33   34   35   36   \
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  3.0  0.0   1.0  1.0  0.0  0.0  0.0   
1   1.0  0.0  2.0  5.0  0.0  0.0  0.0  3.0  0.0   3.0  0.0  0.0  2.0  0.0   
2   2.0  0.0  0.0  0.0  0.0  0.0  0.0  2.0  0.0   3.0  1.0  0.0  1.0  0.0   
3   3.0  0.0  1.0  4.0  1.0  0.0  1.0  2.0  0.0   6.0  2.0  0.0  1.0  0.0   
4   0.0  0.0  0.0  0.0  0.0  0.0  0.0  2.0  0.0   7.0  0.0  0.0  1.0  0.0   
5   0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0   4.0  0.0  2.0  0.0  0.0   
6   2.0  0.0  0.0  2.0  0.0  0.0  1.0  1.0  0.0  11.0  0.0  0.0  1.0  0.0   
7   0.0  0.0  0.0  2.0  0.0  0.0  0.0  2.0  0.0   2.0  0.0  1.0  2.0  0.0   
8   2.0  0.0  1.0  2.0  0.0  0.0  1.0  2.0  0.0   6.0  0.0 

In [43]:
dennis_martinez_starts = all_seasons[(all_seasons[101] == 'martd001') | (all_seasons[103] == 'martd001')]

In [44]:
dennis_martinez_starts

0    1    2    3   4    5    6   7    8    9    10   11  12   13   \
1862   19760926    0  Sun  BOS  AL  157  BAL  AL  156    8    3   54   D  NaN   
1915   19761002    0  Sat  BAL  AL  161  BOS  AL  161    0    1   51   D  NaN   
2450   19770525    2  Wed  KCA  AL   40  BAL  AL   39    2    7   51   N  NaN   
2570   19770604    1  Sat  BAL  AL   48  KCA  AL   47    5    4   54   N  NaN   
2618   19770608    0  Wed  BAL  AL   53  BOS  AL   53    5   14   51   N  NaN   
...         ...  ...  ...  ...  ..  ...  ...  ..  ...  ...  ...  ...  ..  ...   
45461  19980411    0  Sat  ATL  NL   10  PHI  NL    9    5    6   51   N  NaN   
45567  19980419    2  Sun  ATL  NL   18  COL  NL   19    7   10   51   N  NaN   
46079  19980528    0  Thu  MON  NL   52  ATL  NL   54    9    5   54   N  NaN   
46153  19980602    0  Tue  ATL  NL   59  MIL  NL   55    9    0   54   N  NaN   
46247  19980609    0  Tue  BOS  AL   62  ATL  NL   65    9    3   54   N  NaN   

       14   15     16       17     18         19            20    21    22   \
1862   NaN  NaN  BAL11   8272.0  127.0  000030050     000000003  35.0  11.0   
1915   NaN  NaN  BOS07  12753.0  111.0  000000000     10000000x  30.0   5.0   
2450   NaN  NaN  BAL11  11388.0  176.0  010000001     00000214x  32.0   5.0   
2570   NaN  NaN  KAN06  36931.0  141.0  000023000     000001030  35.0   9.0   
2618   NaN  NaN  BOS07  22943.0  198.0  010000040  0(11)300000x  39.0  12.0   
...    ...  ...    ...      ...    ...        ...           ...   ...   ...   
45461  NaN  NaN  PHI12  17676.0  176.0  000001103     20021001x  35.0   9.0   
45567  NaN  NaN  DEN02  43977.0  197.0  003001210     01600030x  37.0  13.0   
46079  NaN  NaN  ATL02  31416.0  192.0  000010224     011002100  36.0  12.0   
46153  NaN  NaN  MIL05  39017.0  165.0  020120040     000000000  36.0  12.0   
46247  NaN  NaN  ATL02  43121.0  183.0  100511010     010011000  38.0  13.0   

       23   24   25   26   27   28   29   30   31   32   33   34   35   36   \
1862   4.0  0.0  0.0  8.0  0.0  0.0  0.0  4.0  0.0  6.0  0.0  1.0  0.0  0.0   
1915   1.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0  3.0  2.0  1.0  2.0  0.0   
2450   1.0  0.0  1.0  2.0  0.0  0.0  1.0  5.0  0.0  1.0  2.0  1.0  1.0  0.0   
2570   1.0  0.0  1.0  5.0  0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0   
2618   2.0  0.0  1.0  5.0  0.0  0.0  0.0  4.0  0.0  6.0  0.0  0.0  1.0  0.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
45461  3.0  0.0  1.0  5.0  0.0  0.0  0.0  7.0  0.0  6.0  0.0  0.0  1.0  0.0   
45567  4.0  0.0  1.0  7.0  0.0  1.0  0.0  7.0  0.0  4.0  0.0  0.0  2.0  0.0   
46079  3.0  0.0  1.0  8.0  1.0  0.0  0.0  5.0  0.0  6.0  2.0  0.0  2.0  0.0   
46153  1.0  3.0  3.0  9.0  1.0  0.0  1.0  7.0  0.0  4.0  1.0  1.0  1.0  0.0   
46247  1.0  1.0  0.0  7.0  0.0  1.0  0.0  4.0  0.0  8.0  1.0  0.0  1.0  0.0   

        37   38    39    40   41   42    43    44   45   46   47   48    49   \
1862    4.0  1.0   1.0   1.0  0.0  0.0  27.0  14.0  1.0  0.0  3.0  0.0  31.0   
1915    7.0  1.0   1.0   1.0  0.0  0.0  24.0  11.0  0.0  0.0  2.0  0.0  27.0   
2450    9.0  4.0   7.0   7.0  0.0  0.0  24.0   7.0  0.0  0.0  0.0  0.0  32.0   
2570    3.0  1.0   2.0   2.0  0.0  0.0  27.0   8.0  1.0  0.0  2.0  0.0  33.0   
2618   11.0  4.0  12.0  12.0  1.0  0.0  24.0   9.0  2.0  0.0  2.0  0.0  33.0   
...     ...  ...   ...   ...  ...  ...   ...   ...  ...  ...  ...  ...   ...   
45461  10.0  5.0   5.0   5.0  0.0  0.0  24.0  12.0  1.0  0.0  1.0  0.0  30.0   
45567  11.0  5.0  10.0  10.0  0.0  0.0  24.0  11.0  0.0  0.0  1.0  0.0  36.0   
46079   6.0  6.0   4.0   4.0  1.0  0.0  27.0   9.0  1.0  0.0  1.0  0.0  34.0   
46153   9.0  1.0   0.0   0.0  0.0  0.0  27.0  15.0  0.0  0.0  3.0  0.0  35.0   
46247   7.0  2.0   3.0   3.0  0.0  0.0  27.0  10.0  0.0  0.0  0.0  0.0  34.0   

        50   51   52   53    54   55   56   57    58   59   60   61   62   \
1862    6.0  0.0  0.0  0.0   3.0  0.0  0.0  0.0   2.0  0.0  3.0  0.0  0.0   
1915    6.0  1.0  1.0  0.0

In [45]:
dennis_martinez_decisions = dennis_martinez_starts[(dennis_martinez_starts[93] == 'martd001') | (dennis_martinez_starts[95] == 'martd001')]

In [46]:
dennis_martinez_decisions

0    1    2    3   4    5    6   7    8    9    10   11  12   13   \
1862   19760926    0  Sun  BOS  AL  157  BAL  AL  156    8    3   54   D  NaN   
1915   19761002    0  Sat  BAL  AL  161  BOS  AL  161    0    1   51   D  NaN   
2450   19770525    2  Wed  KCA  AL   40  BAL  AL   39    2    7   51   N  NaN   
2570   19770604    1  Sat  BAL  AL   48  KCA  AL   47    5    4   54   N  NaN   
2618   19770608    0  Wed  BAL  AL   53  BOS  AL   53    5   14   51   N  NaN   
...         ...  ...  ...  ...  ..  ...  ...  ..  ...  ...  ...  ...  ..  ...   
43651  19970521    0  Wed  SEA  AL   45  ANA  AL   43    3   18   51   N  NaN   
45461  19980411    0  Sat  ATL  NL   10  PHI  NL    9    5    6   51   N  NaN   
45567  19980419    2  Sun  ATL  NL   18  COL  NL   19    7   10   51   N  NaN   
46153  19980602    0  Tue  ATL  NL   59  MIL  NL   55    9    0   54   N  NaN   
46247  19980609    0  Tue  BOS  AL   62  ATL  NL   65    9    3   54   N  NaN   

       14   15     16       17     18         19            20    21    22   \
1862   NaN  NaN  BAL11   8272.0  127.0  000030050     000000003  35.0  11.0   
1915   NaN  NaN  BOS07  12753.0  111.0  000000000     10000000x  30.0   5.0   
2450   NaN  NaN  BAL11  11388.0  176.0  010000001     00000214x  32.0   5.0   
2570   NaN  NaN  KAN06  36931.0  141.0  000023000     000001030  35.0   9.0   
2618   NaN  NaN  BOS07  22943.0  198.0  010000040  0(11)300000x  39.0  12.0   
...    ...  ...    ...      ...    ...        ...           ...   ...   ...   
43651  NaN  NaN  ANA01  20295.0  198.0  010101000     16023510x  36.0  10.0   
45461  NaN  NaN  PHI12  17676.0  176.0  000001103     20021001x  35.0   9.0   
45567  NaN  NaN  DEN02  43977.0  197.0  003001210     01600030x  37.0  13.0   
46153  NaN  NaN  MIL05  39017.0  165.0  020120040     000000000  36.0  12.0   
46247  NaN  NaN  ATL02  43121.0  183.0  100511010     010011000  38.0  13.0   

       23   24   25   26   27   28   29   30   31   32   33   34   35   36   \
1862   4.0  0.0  0.0  8.0  0.0  0.0  0.0  4.0  0.0  6.0  0.0  1.0  0.0  0.0   
1915   1.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0  3.0  2.0  1.0  2.0  0.0   
2450   1.0  0.0  1.0  2.0  0.0  0.0  1.0  5.0  0.0  1.0  2.0  1.0  1.0  0.0   
2570   1.0  0.0  1.0  5.0  0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0   
2618   2.0  0.0  1.0  5.0  0.0  0.0  0.0  4.0  0.0  6.0  0.0  0.0  1.0  0.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
43651  1.0  0.0  1.0  3.0  0.0  0.0  0.0  1.0  0.0  9.0  0.0  0.0  1.0  0.0   
45461  3.0  0.0  1.0  5.0  0.0  0.0  0.0  7.0  0.0  6.0  0.0  0.0  1.0  0.0   
45567  4.0  0.0  1.0  7.0  0.0  1.0  0.0  7.0  0.0  4.0  0.0  0.0  2.0  0.0   
46153  1.0  3.0  3.0  9.0  1.0  0.0  1.0  7.0  0.0  4.0  1.0  1.0  1.0  0.0   
46247  1.0  1.0  0.0  7.0  0.0  1.0  0.0  4.0  0.0  8.0  1.0  0.0  1.0  0.0   

        37   38    39    40   41   42    43    44   45   46   47   48    49   \
1862    4.0  1.0   1.0   1.0  0.0  0.0  27.0  14.0  1.0  0.0  3.0  0.0  31.0   
1915    7.0  1.0   1.0   1.0  0.0  0.0  24.0  11.0  0.0  0.0  2.0  0.0  27.0   
2450    9.0  4.0   7.0   7.0  0.0  0.0  24.0   7.0  0.0  0.0  0.0  0.0  32.0   
2570    3.0  1.0   2.0   2.0  0.0  0.0  27.0   8.0  1.0  0.0  2.0  0.0  33.0   
2618   11.0  4.0  12.0  12.0  1.0  0.0  24.0   9.0  2.0  0.0  2.0  0.0  33.0   
...     ...  ...   ...   ...  ...  ...   ...   ...  ...  ...  ...  ...   ...   
43651   7.0  6.0  16.0  16.0  0.0  0.0  24.0   9.0  3.0  0.0  0.0  0.0  45.0   
45461  10.0  5.0   5.0   5.0  0.0  0.0  24.0  12.0  1.0  0.0  1.0  0.0  30.0   
45567  11.0  5.0  10.0  10.0  0.0  0.0  24.0  11.0  0.0  0.0  1.0  0.0  36.0   
46153   9.0  1.0   0.0   0.0  0.0  0.0  27.0  15.0  0.0  0.0  3.0  0.0  35.0   
46247   7.0  2.0   3.0   3.0  0.0  0.0  27.0  10.0  0.0  0.0  0.0  0.0  34.0   

        50   51   52   53    54   55   56   57    58   59   60   61   62   \
1862    6.0  0.0  0.0  0.0   3.0  0.0  0.0  0.0   2.0  0.0  3.0  0.0  0.0   
1915    6.0  1.0  1.0  0.0

In [47]:
dennis_martinez_starts[dennis_martinez_starts[93] == 'martd001']

0    1    2    3   4    5    6   7    8    9    10   11  12   13   \
2450   19770525    2  Wed  KCA  AL   40  BAL  AL   39    2    7   51   N  NaN   
2570   19770604    1  Sat  BAL  AL   48  KCA  AL   47    5    4   54   N  NaN   
2817   19770625    1  Sat  TOR  AL   67  BAL  AL   69    2    5   51   N  NaN   
2925   19770703    0  Sun  BAL  AL   78  BOS  AL   75   12    8   54   D  NaN   
3643   19770831    0  Wed  CAL  AL  129  BAL  AL  130    3    4   51   N  NaN   
...         ...  ...  ...  ...  ..  ...  ...  ..  ...  ...  ...  ...  ..  ...   
41449  19960526    0  Sun  CLE  AL   47  DET  AL   50    5    0   54   D  NaN   
41501  19960531    0  Fri  CLE  AL   52  MIL  AL   51   10    4   54   N  NaN   
42180  19960724    0  Wed  CLE  AL  101  TOR  AL  101   10    0   54   N  NaN   
43197  19970414    0  Mon  SEA  AL   12  CLE  AL   11    6    1   54   N  NaN   
46153  19980602    0  Tue  ATL  NL   59  MIL  NL   55    9    0   54   N  NaN   

       14   15     16       17     18         19         20    21    22   23   \
2450   NaN  NaN  BAL11  11388.0  176.0  010000001  00000214x  32.0   5.0  1.0   
2570   NaN  NaN  KAN06  36931.0  141.0  000023000  000001030  35.0   9.0  1.0   
2817   NaN  NaN  BAL11  16794.0  129.0  000000110  04000001x  33.0   7.0  1.0   
2925   NaN  NaN  BOS07  31081.0  194.0  001344000  030014000  40.0  16.0  2.0   
3643   NaN  NaN  BAL11   9416.0  172.0  003000000  00020011x  30.0   5.0  1.0   
...    ...  ...    ...      ...    ...        ...        ...   ...   ...  ...   
41449  NaN  NaN  DET04  39056.0  161.0  000010040  000000000  28.0   3.0  1.0   
41501  NaN  NaN  MIL05  24050.0  228.0  021110410  003000010  45.0  18.0  3.0   
42180  NaN  NaN  TOR02  35218.0  172.0  010063000  000000000  37.0  11.0  1.0   
43197  NaN  NaN  CLE08  41184.0  161.0  302000001  000001000  31.0  10.0  3.0   
46153  NaN  NaN  MIL05  39017.0  165.0  020120040  000000000  36.0  12.0  1.0   

       24   25    26   27   28   29   30   31   32   33   34   35   36    37   \
2450   0.0  1.0   2.0  0.0  0.0  1.0  5.0  0.0  1.0  2.0  1.0  1.0  0.0   9.0   
2570   0.0  1.0   5.0  0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0   3.0   
2817   0.0  0.0   2.0  0.0  0.0  0.0  2.0  0.0  5.0  0.0  0.0  2.0  0.0   6.0   
2925   0.0  2.0  12.0  0.0  0.0  1.0  3.0  0.0  8.0  1.0  0.0  1.0  0.0   5.0   
3643   1.0  0.0   3.0  0.0  1.0  0.0  4.0  1.0  5.0  0.0  0.0  1.0  0.0   5.0   
...    ...  ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   
41449  0.0  1.0   4.0  1.0  1.0  0.0  7.0  0.0  6.0  0.0  0.0  2.0  0.0   5.0   
41501  0.0  1.0   8.0  0.0  0.0  2.0  3.0  0.0  7.0  1.0  0.0  1.0  0.0  13.0   
42180  0.0  2.0  10.0  0.0  0.0  1.0  8.0  0.0  3.0  1.0  0.0  3.0  0.0   9.0   
43197  0.0  1.0   6.0  1.0  1.0  1.0  4.0  0.0  4.0  1.0  1.0  1.0  0.0   5.0   
46153  3.0  3.0   9.0  1.0  0.0  1.0  7.0  0.0  4.0  1.0  1.0  1.0  0.0   9.0   

       38   39   40   41   42    43    44   45   46   47   48    49    50   \
2450   4.0  7.0  7.0  0.0  0.0  24.0   7.0  0.0  0.0  0.0  0.0  32.0  10.0   
2570   1.0  2.0  2.0  0.0  0.0  27.0   8.0  1.0  0.0  2.0  0.0  33.0   8.0   
2817   2.0  4.0  4.0  0.0  0.0  24.0  10.0  1.0  1.0  2.0  0.0  28.0   6.0   
2925   3.0  7.0  7.0  0.0  0.0  27.0  10.0  1.0  0.0  0.0  0.0  36.0  10.0   
3643   2.0  4.0  4.0  0.0  0.0  24.0   9.0  2.0  0.0  2.0  0.0  33.0  11.0   
...    ...  ...  ...  ...  ...   ...   ...  ...  ...  ...  ...   ...   ...   
41449  1.0  0.0  0.0  0.0  0.0  27.0  16.0  0.0  0.0  2.0  0.0  32.0   8.0   
41501  3.0  3.0  3.0  0.0  0.0  27.0  10.0  1.0  0.0  0.0  0.0  36.0  10.0   
42180  4.0  0.0  0.0  0.0  0.0  27.0  12.0  0.0  0.0  0.0  0.0  30.0   3.0   
43197  4.0  1.0  1.0  0.0  0.0  27.0  12.0  1.0  0.0  1.0  0.0  28.0   2.0   
46153  1.0  0.0  0.0  0.0  0.0  27.0  15.0  0.0  0.0  3.0  0.0  35.0  12.0   

       51   52   53   54   55   56   57   58   59   60   61   62   63   64   \
2450   3.0  0.0  0.0  7.0  0.0  1.0  1.0  4.0  2.0  7.0  1.0  1.0  0.0  0.0  

In [48]:
# losing stats in starts
len(dennis_martinez_starts[dennis_martinez_starts[95] == 'martd001'])

182

In [49]:
# winning stats in starts
len(dennis_martinez_starts[dennis_martinez_starts[93] == 'martd001'])

230

In [50]:
# lets get number of wins vs hofs
hof_dataset.head()

playerID  yearID votedBy  ballots  needed  votes inducted category  \
0   cobbty01    1936   BBWAA    226.0   170.0  222.0        Y   Player   
1   ruthba01    1936   BBWAA    226.0   170.0  215.0        Y   Player   
2  wagneho01    1936   BBWAA    226.0   170.0  215.0        Y   Player   
3  mathech01    1936   BBWAA    226.0   170.0  205.0        Y   Player   
4  johnswa01    1936   BBWAA    226.0   170.0  189.0        Y   Player   

  needed_note  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN

In [51]:
# lets get hof from dennis' era
pitching_hofs = hof_dataset[hof_dataset.yearID >= 1970]

In [52]:
unique_pitching_ids = pitching_dataset[pitching_dataset.yearID > 1970].playerID.unique()

In [53]:
len(pitching_hofs)

209

In [54]:
pitching_hofs['playerID'].isin(unique_pitching_ids).value_counts()

False    183
True      26
Name: playerID, dtype: int64

In [55]:
pitching_hofs_era = pitching_hofs[pitching_hofs['playerID'].isin(unique_pitching_ids)]

In [56]:
pitching_hofs_era.head()

playerID  yearID votedBy  ballots  needed  votes inducted category  \
2819  gibsobo01    1981   BBWAA    401.0   301.0  337.0        Y   Player   
2905  maricju01    1983   BBWAA    374.0   281.0  313.0        Y   Player   
2983  wilheho01    1985   BBWAA    395.0   297.0  331.0        Y   Player   
3070  hunteca01    1987   BBWAA    413.0   310.0  315.0        Y   Player   
3185  palmeji01    1990   BBWAA    444.0   333.0  411.0        Y   Player   

     needed_note  
2819         NaN  
2905         NaN  
2983         NaN  
3070         NaN  
3185         NaN

In [57]:
# lets get names to pull from game logs db
peoples_df = pd.read_csv('baseballdatabank-master/core/People.csv')
peoples_df.head()
# peoples_df[peoples_df['playerID'].isin(unique_pitching_ids).value_counts()]

playerID  birthYear  birthMonth  birthDay birthCountry birthState  \
0  aardsda01     1981.0        12.0      27.0          USA         CO   
1  aaronha01     1934.0         2.0       5.0          USA         AL   
2  aaronto01     1939.0         8.0       5.0          USA         AL   
3   aasedo01     1954.0         9.0       8.0          USA         CA   
4   abadan01     1972.0         8.0      25.0          USA         FL   

    birthCity  deathYear  deathMonth  deathDay deathCountry deathState  \
0      Denver        NaN         NaN       NaN          NaN        NaN   
1      Mobile        NaN         NaN       NaN          NaN        NaN   
2      Mobile     1984.0         8.0      16.0          USA         GA   
3      Orange        NaN         NaN       NaN          NaN        NaN   
4  Palm Beach        NaN         NaN       NaN          NaN        NaN   

  deathCity nameFirst nameLast       nameGiven  weight  height bats throws  \
0       NaN     David  Aardsma     David Allan   215.0    75.0    R      R   
1       NaN      Hank    Aaron     Henry Louis   180.0    72.0    R      R   
2   Atlanta    Tommie    Aaron      Tommie Lee   190.0    75.0    R      R   
3       NaN       Don     Aase  Donald William   190.0    75.0    R      R   
4       NaN      Andy     Abad   Fausto Andres   184.0    73.0    L      L   

        debut   finalGame   retroID    bbrefID  
0  2004-04-06  2015-08-23  aardd001  aardsda01  
1  1954-04-13  1976-10-03  aaroh101  aaronha01  
2  1962-04-10  1971-09-26  aarot101  aaronto01  
3  1977-07-26  1990-10-03  aased001   aasedo01  
4  2001-09-10  2006-04-13  abada001   abadan01

In [58]:
name_dfs = peoples_df[peoples_df['playerID'].isin(pitching_hofs_era.playerID.unique())][['nameFirst', 'nameLast']]

In [59]:
name_dfs['name'] = name_dfs['nameFirst'] + ' ' +name_dfs['nameLast']

In [60]:
name_dfs.name.unique()
# 26 total

array(['Bert Blyleven', 'Wade Boggs', 'Jim Bunning', 'Steve Carlton',
       'Dennis Eckersley', 'Rollie Fingers', 'Bob Gibson', 'Tom Glavine',
       'Rich Gossage', 'Trevor Hoffman', 'Catfish Hunter',
       'Fergie Jenkins', 'Randy Johnson', 'Greg Maddux', 'Juan Marichal',
       'Pedro Martinez', 'Jack Morris', 'Phil Niekro', 'Jim Palmer',
       'Gaylord Perry', 'Nolan Ryan', 'Tom Seaver', 'John Smoltz',
       'Bruce Sutter', 'Don Sutton', 'Hoyt Wilhelm'], dtype=object)

In [61]:
# all_seasons[all_seasons[96].isin(name_dfs.name.unique())][[95,96]][0:20]
all_seasons[all_seasons[96] == 'John Smoltz'][95]

25678    smolj001
25742    smolj001
25813    smolj001
26003    smolj001
26243    smolj001
           ...   
44971    smolj001
45107    smolj001
45937    smolj001
46483    smolj001
47368    smolj001
Name: 95, Length: 105, dtype: object

In [62]:
# Jim Palmer = palmj001
# Gaylord Perry = perrg101
# Tom Seaver = seavt001
# Phil Niekro = niekp001
# Catfish Hunter = huntj101
# Tom Glavine = glavt001
# John Smoltz = smolj001
# Randy Johnson = johnr005
# Pedro Martinez = martp001
# Greg Maddux = maddg002
# Fergie Jenkins = jenkf101
# Don Sutton = suttd001
# Nolan Ryan = ryann001
# Dennis Eckersley = ecked001
# Trevor Hoffman = hofft001
# Bert Blyleven = blylb001
# Rich Gossage = gossr001
# Steve Carlton = carls001
# Jack Morris = morrj001
# Bruce Sutter = suttb001
# Bob Gibson = gibsb001
# Rollie Fingers = fingr001

In [63]:
hof_ids = ["palmj001", "perrg101", "seavt001", "niekp001", "huntj101", "glavt001", "smolj001", "johnr005",
          "martp001", "maddg002", "jenkf101", "suttd001", "ryann001", "ecked001", "hofft001", "blylb001",
           "gossr001", "carls001", "morrj001", "suttb001", "gibsb001", "fingr001"]
len(hof_ids)

22

In [64]:
len(dennis_martinez_starts[(dennis_martinez_starts[93] == 'martd001') & (dennis_martinez_starts[95].isin(hof_ids))])

6

In [65]:
len(dennis_martinez_starts[(dennis_martinez_starts[95] == 'martd001') & (dennis_martinez_starts[93].isin(hof_ids))])

8

In [66]:
dennis_martinez_starts[(dennis_martinez_starts[93] == 'martd001') & (dennis_martinez_starts[95].isin(hof_ids))]

0    1    2    3   4    5    6   7    8    9    10   11  12   13   \
4703   19780606    0  Tue  BAL  AL   54  CAL  AL   51    8    6   54   N  NaN   
10675  19810509    1  Sat  BAL  AL   22  TEX  AL   24    7    3   54   N  NaN   
31396  19910610    0  Mon  MON  NL   56  ATL  NL   53    7    1   54   N  NaN   
31459  19910615    0  Sat  ATL  NL   58  MON  NL   61    0    2   51   N  NaN   
33309  19920522    0  Fri  ATL  NL   43  MON  NL   38    1    7   51   N  NaN   
35808  19930618    0  Fri  ATL  NL   68  MON  NL   67    1    2   51   N  NaN   

       14   15     16       17     18         19         20    21    22   23   \
4703   NaN  NaN  ANA01  15864.0  198.0  011032010  101020020  37.0  15.0  1.0   
10675  NaN  NaN  ARL01      0.0  139.0  010202002  000000003  39.0  14.0  3.0   
31396  NaN  NaN  ATL01  19853.0  192.0  001200013  100000000  35.0  12.0  2.0   
31459  NaN  NaN  MON02  16586.0  175.0  000000000  10001000x  34.0   8.0  1.0   
33309  NaN  NaN  MON02  20313.0  154.0  000000010  00000160x  28.0   2.0  0.0   
35808  NaN  NaN  MON02  19519.0  144.0  000000100  00000200x  30.0   4.0  1.0   

       24   25   26   27   28   29   30   31   32   33   34   35   36   37   \
4703   1.0  0.0  8.0  0.0  1.0  1.0  4.0  0.0  5.0  4.0  1.0  3.0  0.0  8.0   
10675  0.0  1.0  7.0  0.0  0.0  1.0  3.0  1.0  5.0  1.0  1.0  1.0  0.0  9.0   
31396  0.0  2.0  5.0  0.0  1.0  0.0  5.0  0.0  6.0  1.0  1.0  1.0  0.0  7.0   
31459  1.0  0.0  0.0  0.0  0.0  0.0  2.0  0.0  5.0  0.0  0.0  1.0  0.0  9.0   
33309  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0  1.0  0.0  0.0  0.0   
35808  0.0  1.0  1.0  0.0  0.0  0.0  3.0  0.0  7.0  3.0  0.0  1.0  0.0  5.0   

       38   39   40   41   42    43    44   45   46   47   48    49    50   \
4703   4.0  5.0  5.0  1.0  0.0  27.0  10.0  3.0  0.0  1.0  0.0  37.0  10.0   
10675  2.0  3.0  3.0  0.0  0.0  27.0  10.0  1.0  0.0  2.0  0.0  32.0   7.0   
31396  3.0  1.0  1.0  0.0  0.0  27.0  11.0  0.0  0.0  1.0  0.0  32.0   7.0   
31459  4.0  2.0  2.0  0.0  0.0  24.0  10.0  0.0  0.0  2.0  0.0  28.0   9.0   
33309  4.0  7.0  7.0  1.0  0.0  24.0  13.0  0.0  0.0  0.0  0.0  32.0   9.0   
35808  2.0  2.0  2.0  0.0  0.0  24.0   7.0  1.0  0.0  2.0  0.0  25.0   4.0   

       51   52   53   54   55   56   57   58   59   60   61   62   63   64   \
4703   0.0  1.0  0.0  6.0  0.0  0.0  1.0  3.0  0.0  3.0  0.0  0.0  1.0  0.0   
10675  2.0  0.0  0.0  3.0  0.0  0.0  0.0  1.0  0.0  3.0  1.0  0.0  2.0  0.0   
31396  2.0  0.0  1.0  1.0  0.0  0.0  0.0  2.0  0.0  5.0  0.0  0.0  1.0  0.0   
31459  1.0  0.0  0.0  2.0  1.0  1.0  0.0  2.0  0.0  9.0  2.0  1.0  0.0  0.0   
33309  3.0  0.0  0.0  7.0  0.0  0.0  0.0  3.0  0.0  0.0  1.0  1.0  0.0  0.0   
35808  2.0  0.0  0.0  2.0  0.0  0.0  0.0  4.0  0.0  8.0  0.0  1.0  1.0  0.0   

       65   66   67   68   69   70    71    72   73   74   75   76        77   \
4703   8.0  2.0  8.0  8.0  0.0  0.0  27.0  12.0  0.0  0.0  3.0  0.0  merrd901   
10675  3.0  2.0  7.0  7.0  0.0  0.0  27.0  14.0  0.0  0.0  1.0  0.0  mccol901   
31396  6.0  2.0  7.0  7.0  1.0  0.0  27.0  11.0  1.0  0.0  2.0  0.0  tatat901   
31459  6.0  1.0  0.0  0.0  1.0  0.0  27.0  12.0  0.0  0.0  1.0  0.0  bonig901   
33309  4.0  1.0  1.0  1.0  0.0  0.0  27.0  11.0  0.0  0.0  0.0  0.0  wintm901   
35808  3.0  2.0  1.0  1.0  0.0  0.0  27.0  11.0  0.0  0.0  1.0  0.0  ripps901   

                   78        79                 80        81              82   \
4703   Durwood Merrill  sprim901  Marty Springstead  barnl901   Larry Barnett   
10675      Larry McCoy  merrd901    Durwood Merrill  phild901   Dave Phillips   
31396       Terry Tata  ripps901      Steve Rippley  hohnb901       Bill Hohn   
31459       Greg Bonin  monte901        Ed Montague  rapue901      Ed Rapuano   
33309     Mike Winters  cuzzp901         Phil Cuzzi  monte901     Ed Montague   
35808    Steve Rippley  quicj901          Jim Quick  crawj901  Jerry Crawford   

            83               84   85      86   87      88        89   \
4703   evanj9

In [67]:
dennis_martinez_starts[(dennis_martinez_starts[95] == 'martd001') & (dennis_martinez_starts[93].isin(hof_ids))]

0    1    2    3   4    5    6   7    8    9    10   11  12   13   \
5509   19780811    0  Fri  NYA  AL  114  BAL  AL  114    2    1   33   N  NaN   
8099   19790919    0  Wed  BAL  AL  150  DET  AL  152    0    5   51   N  NaN   
9733   19800816    0  Sat  NYA  AL  115  BAL  AL  114    4    1   54   N  NaN   
11891  19820421    0  Wed  BAL  AL   11  BOS  AL   12    5    6   51   N  NaN   
15188  19830802    1  Tue  BAL  AL  100  CLE  AL  103    1    3   51   N  NaN   
28521  19890926    0  Tue  CHN  NL  158  MON  NL  158    3    2   54   N  NaN   
29525  19900629    0  Fri  ATL  NL   71  MON  NL   75    4    2   54   N  NaN   
37029  19930923    0  Thu  ATL  NL  153  MON  NL  153    6    3   54   N  NaN   

       14   15     16       17     18         19         20    21    22   23   \
5509   NaN  NaN  BAL11  29539.0  147.0     000200     10000x  22.0   5.0  1.0   
8099   NaN  NaN  DET04  12573.0  138.0  000000000  10101110x  28.0   4.0  0.0   
9733   NaN  NaN  BAL11  51649.0  185.0  100020010  000010000  34.0   7.0  1.0   
11891  NaN  NaN  BOS07  15725.0  166.0  110000300  00600000x  39.0  12.0  3.0   
15188  NaN  NaN  CLE07      0.0  169.0  000000001  00200100x  32.0   6.0  1.0   
28521  NaN  NaN  MON02  11615.0  175.0  010001010  000002000  33.0   8.0  1.0   
29525  NaN  NaN  MON02  14210.0  172.0  000101200  000100010  32.0   6.0  0.0   
37029  NaN  NaN  MON02  25219.0  152.0  000050010  100001001  34.0   8.0  2.0   

       24   25   26   27   28   29   30   31    32   33   34   35   36    37   \
5509   0.0  0.0  1.0  0.0  0.0  0.0  3.0  0.0   2.0  1.0  0.0  0.0  0.0   5.0   
8099   0.0  0.0  0.0  0.0  0.0  1.0  3.0  0.0   7.0  0.0  0.0  3.0  0.0   5.0   
9733   0.0  2.0  4.0  0.0  0.0  0.0  6.0  1.0   7.0  1.0  0.0  0.0  0.0   9.0   
11891  0.0  0.0  5.0  0.0  1.0  0.0  3.0  0.0  11.0  0.0  0.0  0.0  0.0  11.0   
15188  0.0  0.0  1.0  0.0  0.0  0.0  5.0  0.0   4.0  0.0  0.0  1.0  0.0   9.0   
28521  1.0  0.0  2.0  0.0  0.0  0.0  2.0  1.0   7.0  0.0  1.0  1.0  0.0   5.0   
29525  0.0  1.0  4.0  0.0  0.0  0.0  4.0  0.0   9.0  0.0  1.0  0.0  0.0   5.0   
37029  0.0  0.0  5.0  1.0  0.0  1.0  2.0  0.0   4.0  3.0  0.0  1.0  0.0   5.0   

       38   39   40   41   42    43    44   45   46   47   48    49    50   \
5509   1.0  1.0  1.0  1.0  0.0  15.0   2.0  0.0  0.0  0.0  0.0  19.0   4.0   
8099   2.0  5.0  5.0  0.0  0.0  24.0   9.0  2.0  0.0  0.0  0.0  30.0   8.0   
9733   2.0  1.0  1.0  0.0  0.0  27.0  11.0  0.0  0.0  0.0  0.0  32.0   5.0   
11891  4.0  6.0  6.0  0.0  0.0  24.0  10.0  1.0  0.0  2.0  0.0  32.0  11.0   
15188  2.0  1.0  1.0  0.0  0.0  24.0  10.0  2.0  0.0  1.0  0.0  33.0   8.0   
28521  2.0  2.0  2.0  0.0  0.0  27.0   9.0  1.0  0.0  0.0  0.0  32.0   7.0   
29525  2.0  2.0  2.0  0.0  0.0  27.0  17.0  2.0  0.0  1.0  0.0  32.0   5.0   
37029  2.0  2.0  2.0  0.0  0.0  27.0  16.0  1.0  0.0  1.0  0.0  31.0   7.0   

       51   52   53   54   55   56   57   58   59   60   61   62   63   64   \
5509   0.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0   
8099   2.0  1.0  0.0  3.0  1.0  0.0  0.0  3.0  0.0  4.0  3.0  1.0  0.0  0.0   
9733   1.0  0.0  1.0  1.0  0.0  0.0  0.0  2.0  0.0  6.0  0.0  0.0  0.0  0.0   
11891  1.0  0.0  0.0  6.0  0.0  0.0  0.0  4.0  0.0  5.0  0.0  1.0  1.0  0.0   
15188  2.0  0.0  0.0  3.0  1.0  0.0  0.0  0.0  0.0  5.0  0.0  0.0  1.0  0.0   
28521  1.0  0.0  0.0  2.0  2.0  1.0  0.0  1.0  1.0  7.0  2.0  0.0  0.0  0.0   
29525  1.0  0.0  2.0  2.0  1.0  0.0  0.0  3.0  0.0  6.0  0.0  0.0  1.0  0.0   
37029  1.0  1.0  0.0  3.0  0.0  2.0  0.0  4.0  1.0  5.0  1.0  0.0  1.0  0.0   

       65   66   67   68   69   70    71    72   73   74   75   76        77   \
5509   4.0  1.0  1.0  1.0  0.0  0.0  18.0   8.0  1.0  0.0  0.0  0.0  pales901   
8099   5.0  1.0  0.0  0.0  2.0  0.0  27.0  15.0  0.0  0.0  3.0  0.0  fordd901   
9733   6.0  2.0  4.0  4.0  0.0  1.0  27.0   7.0  0.0  0.0  0.0  0.0  pales901   
11891  6.0  2.0  5.0  5.0  0.0  0.0  27.0   6.0  1.0  0.0  0.0  0.0  malog901   
15

In [68]:
cy_young_winners = pitching_awards[(pitching_awards['awardID'] == 'Cy Young Award') & (pitching_awards.yearID < 1999)]
cy_young_winners.head()

playerID         awardID  yearID lgID  tie notes
3173   lylesp01  Cy Young Award    1977   AL  NaN   NaN
3174  carltst01  Cy Young Award    1977   NL  NaN   NaN
3234  guidrro01  Cy Young Award    1978   AL  NaN   NaN
3235  perryga01  Cy Young Award    1978   NL  NaN   NaN
3295  flanami01  Cy Young Award    1979   AL  NaN   NaN

In [69]:
cy_name_dfs = peoples_df[peoples_df['playerID'].isin(cy_young_winners.playerID.unique())][['nameFirst', 'nameLast']]
cy_name_dfs['name'] = cy_name_dfs['nameFirst'] + ' ' +cy_name_dfs['nameLast']

In [70]:
cy_name_dfs.name.unique()

array(['Steve Bedrosian', 'Steve Carlton', 'Roger Clemens', 'David Cone',
       'Mark Davis', 'John Denny', 'Doug Drabek', 'Dennis Eckersley',
       'Rollie Fingers', 'Mike Flanagan', 'Tom Glavine', 'Dwight Gooden',
       'Ron Guidry', 'Pat Hentgen', 'Willie Hernandez', 'Orel Hershiser',
       'LaMarr Hoyt', 'Randy Johnson', 'Sparky Lyle', 'Greg Maddux',
       'Pedro Martinez', 'Jack McDowell', 'Gaylord Perry',
       'Bret Saberhagen', 'Mike Scott', 'John Smoltz', 'Steve Stone',
       'Rick Sutcliffe', 'Bruce Sutter', 'Fernando Valenzuela',
       'Frank Viola', 'Pete Vuckovich', 'Bob Welch'], dtype=object)

In [71]:
len(cy_name_dfs.name.unique())

33

In [72]:
all_seasons[all_seasons[95] == 'martp002']

0    1    2    3   4    5    6   7    8    9    10   11  12   13   \
36802  19930905    0  Sun  SDN  NL  137  ATL  NL  137    2    3   51   D  NaN   
37587  19940509    0  Mon  CIN  NL   32  SDN  NL   31    3    2   54   N  NaN   
38617  19940731    0  Sun  CIN  NL  105  SDN  NL  107    2    1   60   D  NaN   
44869  19970826    0  Tue  CIN  NL  130  COL  NL  133    5    9   51   N  NaN   

       14   15     16       17     18          19          20    21    22   \
36802  NaN  NaN  ATL01  48463.0  149.0   010010000   10000002x  30.0   6.0   
37587  NaN  NaN  SAN01  12764.0  156.0   000001200   000011000  34.0   9.0   
38617  NaN  NaN  SAN01  28147.0  186.0  0001000001  0000001000  34.0   6.0   
44869  NaN  NaN  DEN02  48063.0  191.0   203000000   03020004x  32.0  10.0   

       23   24   25   26   27   28   29   30   31   32   33   34   35   36   \
36802  2.0  0.0  0.0  2.0  1.0  0.0  0.0  4.0  0.0  7.0  0.0  1.0  1.0  0.0   
37587  4.0  0.0  0.0  1.0  2.0  0.0  0.0  1.0  0.0  4.0  3.0  0.0  0.0  0.0   
38617  1.0  0.0  1.0  2.0  2.0  0.0  0.0  8.0  3.0  4.0  0.0  0.0  0.0  0.0   
44869  0.0  0.0  3.0  5.0  2.0  0.0  1.0  6.0  0.0  6.0  1.0  1.0  2.0  0.0   

        37   38   39   40   41   42    43    44   45   46   47   48    49   \
36802   6.0  3.0  3.0  3.0  0.0  0.0  24.0  10.0  0.0  0.0  1.0  0.0  31.0   
37587   7.0  4.0  2.0  2.0  1.0  0.0  27.0   6.0  1.0  0.0  0.0  0.0  31.0   
38617  12.0  2.0  1.0  1.0  0.0  0.0  30.0  14.0  0.0  0.0  2.0  0.0  33.0   
44869   9.0  4.0  9.0  9.0  0.0  0.0  24.0  10.0  0.0  0.0  1.0  0.0  32.0   

        50   51   52   53   54   55   56   57   58   59    60   61   62   63   \
36802   9.0  1.0  0.0  1.0  3.0  0.0  0.0  0.0  3.0  0.0   4.0  1.0  1.0  1.0   
37587   4.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  2.0  1.0   9.0  1.0  0.0  0.0   
38617   6.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  2.0  0.0  10.0  1.0  1.0  2.0   
44869  10.0  1.0  0.0  4.0  9.0  1.0  0.0  0.0  5.0  0.0   6.0  0.0  0.0  0.0   

       64   65   66   67   68   69   70    71    72   73   74   75   76   \
36802  0.0  7.0  1.0  2.0  2.0  0.0  0.0  27.0  10.0  1.0  0.0  1.0  0.0   
37587  0.0  4.0  3.0  3.0  3.0  2.0  0.0  27.0  13.0  0.0  0.0  0.0  0.0   
38617  0.0  5.0  4.0  2.0  2.0  0.0  0.0  30.0  10.0  0.0  0.0  0.0  0.0   
44869  0.0  5.0  4.0  2.0  2.0  1.0  0.0  27.0  15.0  1.0  0.0  2.0  0.0   

            77                78        79             80        81   \
36802  relic901  Charlie Reliford  demud901    Dana DeMuth  laynj901   
37587  pullf901       Frank Pulli  bonig901     Greg Bonin  rapue901   
38617  grege901        Eric Gregg  gormb901   Brian Gorman  ripps901   
44869  kellj901      Jeff Kellogg  vanol901  Larry Vanover  riekr901   

                 82        83             84   85      86   87      88   \
36802    Jerry Layne  rungp901     Paul Runge  NaN  (none)  NaN  (none)   
37587     Ed Rapuano  westj901       Joe West  NaN  (none)  NaN  (none)   
38617  Steve Rippley  tatat901     Terry Tata  NaN  (none)  NaN  (none)   
44869    Rich Rieker  poncl901  Larry Poncino  NaN  (none)  NaN  (none)   

            89             90        91             92        93   \
36802  riggj801  Jim Riggleman  cox-b103      Bobby Cox  maddg002   
37587  johnd105  Davey Johnson  riggj801  Jim Riggleman  ruffj001   
38617  johnd105  Davey Johnson  riggj801  Jim Riggleman  branj001   
44869  mckej801    Jack McKeon  bayld001     Don Baylor  dejem001   

                 94        95              96        97             98   \
36802    Greg Maddux  martp002  Pedro Martinez       NaN         (none)   
37587  Johnny Ruffin  martp002  Pedro Martinez  branj001  Jeff Brantley   
38617  Jeff Brantley  martp002  Pedro Martinez       NaN         (none)   
44869    Mike DeJean  martp002  Pedro Martinez       NaN         (none)   

            99             100       101               102       103  \
36802  justd001  David Justice  worrt002       Tim Worrell  maddg002   
37587       NaN         (none)  browt0

In [73]:
cy_young_ids = list(all_seasons[all_seasons[96].isin(cy_name_dfs.name.unique())][95].unique())

In [74]:
len(dennis_martinez_starts[(dennis_martinez_starts[93] == 'martd001') & (dennis_martinez_starts[95].isin(cy_young_ids))])

15

In [75]:
len(dennis_martinez_starts[(dennis_martinez_starts[95] == 'martd001') & (dennis_martinez_starts[93].isin(cy_young_ids))])

25

In [76]:
dennis_martinez_starts[(dennis_martinez_starts[93] == 'martd001') 
                       & (dennis_martinez_starts[95].isin(cy_young_ids)) 
                       & ((dennis_martinez_starts[3] == 'MON')
                           | (dennis_martinez_starts[5] == 'MON')) ]

/Users/rmartinez/.pyenv/versions/3.8.1/envs/jupyter_notebook_3.8/lib/python3.8/site-packages/pandas/core/ops/array_ops.py:253: FutureWarning:

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison



0    1    2    3   4    5    6   7    8    9    10   11  12   13   \
25056  19880604    0  Sat  MON  NL   53  PIT  NL   54    7    3   54   N  NaN   
26879  19890509    0  Tue  MON  NL   33  HOU  NL   32    4    2   54   N  NaN   
30003  19900808    0  Wed  MON  NL  110  PIT  NL  108    6    2   54   N  NaN   
30692  19910408    0  Mon  MON  NL    1  PIT  NL    1    7    0   54   N  NaN   
31396  19910610    0  Mon  MON  NL   56  ATL  NL   53    7    1   54   N  NaN   
32852  19920411    0  Sat  MON  NL    5  NYN  NL    6    9    2   54   D  NaN   

       14   15     16       17     18         19         20    21    22   23   \
25056  NaN  NaN  PIT07  30669.0  192.0  200400010  000002100  35.0  12.0  0.0   
26879  NaN  NaN  HOU02  10665.0  164.0  102000001  000000002  34.0   9.0  1.0   
30003  NaN  NaN  PIT07  21180.0  159.0  000011400  001000100  36.0  10.0  4.0   
30692  NaN  NaN  PIT07  54274.0  171.0  110022100  000000000  40.0  15.0  2.0   
31396  NaN  NaN  ATL01  19853.0  192.0  001200013  100000000  35.0  12.0  2.0   
32852  NaN  NaN  NYC17  22967.0  205.0  000400032  000001001  39.0  12.0  3.0   

       24   25   26   27   28   29   30   31    32   33   34   35   36   37   \
25056  0.0  1.0  6.0  1.0  0.0  0.0  3.0  0.0   4.0  0.0  1.0  1.0  0.0  5.0   
26879  0.0  1.0  4.0  1.0  1.0  0.0  1.0  1.0   4.0  4.0  0.0  0.0  0.0  6.0   
30003  1.0  0.0  6.0  0.0  0.0  0.0  2.0  0.0   7.0  0.0  0.0  1.0  0.0  5.0   
30692  0.0  2.0  6.0  0.0  0.0  0.0  1.0  0.0   4.0  1.0  0.0  1.0  0.0  7.0   
31396  0.0  2.0  5.0  0.0  1.0  0.0  5.0  0.0   6.0  1.0  1.0  1.0  0.0  7.0   
32852  0.0  0.0  8.0  0.0  0.0  0.0  4.0  1.0  13.0  5.0  1.0  0.0  0.0  7.0   

       38   39   40   41   42    43    44   45   46   47   48    49   50   \
25056  3.0  3.0  3.0  0.0  0.0  27.0  12.0  0.0  0.0  0.0  0.0  34.0  7.0   
26879  2.0  2.0  2.0  0.0  0.0  27.0  11.0  1.0  0.0  1.0  0.0  31.0  5.0   
30003  1.0  2.0  2.0  0.0  0.0  27.0  13.0  1.0  0.0  1.0  0.0  31.0  6.0   
30692  3.0  0.0  0.0  0.0  0.0  27.0   5.0  3.0  0.0  0.0  0.0  30.0  1.0   
31396  3.0  1.0  1.0  0.0  0.0  27.0  11.0  0.0  0.0  1.0  0.0  32.0  7.0   
32852  2.0  2.0  2.0  0.0  0.0  27.0  11.0  0.0  0.0  1.0  0.0  30.0  6.0   

       51   52   53   54   55   56   57   58   59   60   61   62   63   64   \
25056  0.0  1.0  0.0  3.0  0.0  0.0  0.0  6.0  0.0  6.0  1.0  0.0  0.0  0.0   
26879  1.0  0.0  0.0  2.0  0.0  1.0  0.0  4.0  0.0  4.0  2.0  0.0  1.0  0.0   
30003  2.0  0.0  0.0  2.0  0.0  0.0  0.0  1.0  0.0  5.0  2.0  1.0  1.0  0.0   
30692  0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0  7.0  1.0  0.0  0.0  0.0   
31396  2.0  0.0  1.0  1.0  0.0  0.0  0.0  2.0  0.0  5.0  0.0  0.0  1.0  0.0   
32852  2.0  0.0  0.0  2.0  0.0  1.0  0.0  4.0  0.0  5.0  0.0  1.0  1.0  0.0   

        65   66   67   68   69   70    71    72   73   74   75   76   \
25056  10.0  5.0  5.0  5.0  0.0  0.0  27.0  17.0  1.0  0.0  2.0  0.0   
26879   7.0  2.0  4.0  4.0  0.0  0.0  27.0   7.0  0.0  0.0  0.0  0.0   
30003   3.0  3.0  6.0  6.0  0.0  0.0  27.0  18.0  0.0  0.0  1.0  0.0   
30692   7.0  4.0  4.0  4.0  0.0  0.0  27.0  13.0  2.0  0.0  1.0  0.0   
31396   6.0  2.0  7.0  7.0  1.0  0.0  27.0  11.0  1.0  0.0  2.0  0.0   
32852   6.0  2.0  4.0  4.0  1.0  0.0  27.0   8.0  2.0  0.0  0.0  0.0   

            77             78        79              80        81   \
25056  kiblj901    John Kibler  grege901      Eric Gregg  quicj901   
26879  mcshj901  John McSherry  crawj901  Jerry Crawford  hallt901   
30003  harvd901    Doug Harvey  hallt901     Tom Hallion  demud901   
30692  willb902    Bob Willman  martb901   Bruce Martine  janud901   
31396  tatat901     Terry Tata  ripps901   Steve Rippley  hohnb901   
32852  rungp901     Paul Runge  hallt901     Tom Hallion  quicj901   

               82        83              84   85      86   87      88   \
25056    Jim Quick  palld901    Dave Pallone  NaN  (none)  NaN  (none)   
26879  Tom Hallion  westj901        Joe West  NaN  (none)  NaN  (none)   
300

In [77]:
dennis_martinez_starts[(dennis_martinez_starts[95] == 'martd001') 
                       & (dennis_martinez_starts[93].isin(cy_young_ids)) 
                       & ((dennis_martinez_starts[3] == 'MON')
                           | (dennis_martinez_starts[5] == 'MON')) ]

/Users/rmartinez/.pyenv/versions/3.8.1/envs/jupyter_notebook_3.8/lib/python3.8/site-packages/pandas/core/ops/array_ops.py:253: FutureWarning:

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison



0    1    2    3   4    5    6   7    8    9    10   11  12   13   \
21401  19860725    0  Fri  MON  NL   93  CIN  NL   94    2    9   51   N  NaN   
25949  19880819    0  Fri  MON  NL  122  LAN  NL  122    0    2   51   N  NaN   
30746  19910413    0  Sat  MON  NL    6  NYN  NL    6    3    5   51   D  NaN   
32796  19920406    0  Mon  MON  NL    1  PIT  NL    1    0    2   51   N  NaN   

       14   15     16       17     18         19         20    21   22   23   \
21401  NaN  NaN  CIN08  22454.0  144.0  020000000  01033101x  31.0  5.0  2.0   
25949  NaN  NaN  LOS03  36217.0  135.0  000000000  00020000x  33.0  5.0  2.0   
30746  NaN  NaN  NYC17  26046.0  204.0  110000001  10200200x  32.0  7.0  2.0   
32796  NaN  NaN  PIT07  48800.0  153.0  000000000  02000000x  31.0  6.0  1.0   

       24   25   26   27   28   29   30   31    32   33   34   35   36   37   \
21401  0.0  1.0  2.0  0.0  0.0  0.0  1.0  0.0   5.0  0.0  1.0  0.0  0.0  3.0   
25949  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   8.0  0.0  0.0  0.0  0.0  7.0   
30746  0.0  0.0  3.0  0.0  1.0  0.0  3.0  0.0  14.0  2.0  1.0  0.0  0.0  6.0   
32796  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   3.0  0.0  0.0  2.0  0.0  5.0   

       38   39   40   41   42    43    44   45   46   47   48    49    50   \
21401  3.0  8.0  8.0  1.0  0.0  24.0  13.0  2.0  1.0  2.0  0.0  33.0  12.0   
25949  1.0  2.0  2.0  0.0  0.0  24.0  11.0  1.0  0.0  1.0  0.0  28.0   6.0   
30746  3.0  4.0  4.0  0.0  0.0  24.0  10.0  0.0  1.0  0.0  0.0  31.0   7.0   
32796  2.0  2.0  2.0  0.0  0.0  24.0   9.0  3.0  0.0  0.0  0.0  27.0   4.0   

       51   52   53   54   55   56   57   58   59   60   61   62   63   64   \
21401  2.0  0.0  3.0  8.0  1.0  0.0  0.0  7.0  2.0  5.0  1.0  1.0  1.0  0.0   
25949  0.0  0.0  1.0  2.0  0.0  0.0  0.0  0.0  0.0  5.0  0.0  1.0  1.0  0.0   
30746  2.0  0.0  1.0  5.0  0.0  1.0  1.0  6.0  0.0  7.0  2.0  0.0  0.0  0.0   
32796  0.0  0.0  0.0  2.0  0.0  1.0  0.0  2.0  0.0  5.0  2.0  0.0  0.0  0.0   

        65   66   67   68   69   70    71    72   73   74   75   76   \
21401   8.0  1.0  2.0  2.0  0.0  0.0  27.0  15.0  0.0  0.0  0.0  0.0   
25949   2.0  1.0  0.0  0.0  0.0  0.0  27.0  13.0  2.0  0.0  0.0  0.0   
30746  10.0  1.0  3.0  3.0  1.0  0.0  27.0   7.0  1.0  0.0  0.0  0.0   
32796   4.0  2.0  0.0  0.0  0.0  0.0  27.0  16.0  0.0  0.0  2.0  0.0   

            77                78        79              80        81   \
21401  brocf901  Fred Brocklander  weyel901       Lee Weyer  rennd901   
25949  monte901       Ed Montague  bonig901      Greg Bonin  brocf901   
30746  tatat901        Terry Tata  crawj901  Jerry Crawford  ripps901   
32796  tatat901        Terry Tata  westj901        Joe West  rennd901   

                    82        83             84   85      86   87      88   \
21401     Dutch Rennert  monte901    Ed Montague  NaN  (none)  NaN  (none)   
25949  Fred Brocklander  pullf901    Frank Pulli  NaN  (none)  NaN  (none)   
30746     Steve Rippley  hohnb901      Bill Hohn  NaN  (none)  NaN  (none)   
32796     Dutch Rennert  ripps901  Steve Rippley  NaN  (none)  NaN  (none)   

            89            90        91             92        93   \
21401  rodgb102  Buck Rodgers  rosep001      Pete Rose  dennj001   
25949  rodgb102  Buck Rodgers  lasot101    Tom Lasorda  herso001   
30746  rodgb102  Buck Rodgers  harrb101  Bud Harrelson  goodd001   
32796  runnt001  Tom Runnells  leylj801    Jim Leyland  drabd001   

                  94        95               96        97           98   \
21401      John Denny  martd001  Dennis Martinez       NaN       (none)   
25949  Orel Hershiser  martd001  Dennis Martinez       NaN       (none)   
30746   Dwight Gooden  martd001  Dennis Martinez       NaN       (none)   
32796     Doug Drabek  martd001  Dennis Martinez  masor001  Roger Mason   

            99               100       101              102       103  \
21401       NaN           (none)  martd001  Dennis Martinez  dennj001   
25949  marsm001    Mike Marshall  ma

In [78]:
dennis_martinez_starts[(dennis_martinez_starts[93] == 'martd001') 
                       & (dennis_martinez_starts[95].isin(cy_young_ids)) ]

0    1    2    3   4    5    6   7    8    9    10   11  12   13   \
11130  19810815    0  Sat  CHA  AL   59  BAL  AL   60    0    4   51   N  NaN   
13808  19821001    1  Fri  MIL  AL  160  BAL  AL  160    3    8   51   N  NaN   
23065  19870615    0  Mon  NYN  NL   61  MON  NL   61    0    4   51   N  NaN   
25056  19880604    0  Sat  MON  NL   53  PIT  NL   54    7    3   54   N  NaN   
26879  19890509    0  Tue  MON  NL   33  HOU  NL   32    4    2   54   N  NaN   
28640  19900414    0  Sat  NYN  NL    5  MON  NL    5    5    6   51   D  NaN   
30003  19900808    0  Wed  MON  NL  110  PIT  NL  108    6    2   54   N  NaN   
30692  19910408    0  Mon  MON  NL    1  PIT  NL    1    7    0   54   N  NaN   
30809  19910419    0  Fri  NYN  NL   11  MON  NL   11    1    2   51   N  NaN   
31396  19910610    0  Mon  MON  NL   56  ATL  NL   53    7    1   54   N  NaN   
31459  19910615    0  Sat  ATL  NL   58  MON  NL   61    0    2   51   N  NaN   
32852  19920411    0  Sat  MON  NL    5  NYN  NL    6    9    2   54   D  NaN   
33309  19920522    0  Fri  ATL  NL   43  MON  NL   38    1    7   51   N  NaN   
35808  19930618    0  Fri  ATL  NL   68  MON  NL   67    1    2   51   N  NaN   
36689  19930827    0  Fri  HOU  NL  128  MON  NL  130    1    3   51   N  NaN   

       14   15     16       17     18         19         20    21    22   23   \
11130  NaN  NaN  BAL11  15323.0  156.0  000000000  00040000x  31.0   3.0  1.0   
13808  NaN  NaN  BAL11      0.0  183.0  010002000  03110201x  38.0  12.0  2.0   
23065  NaN  NaN  MON02  16465.0  166.0  000000000  10012000x  31.0   3.0  1.0   
25056  NaN  NaN  PIT07  30669.0  192.0  200400010  000002100  35.0  12.0  0.0   
26879  NaN  NaN  HOU02  10665.0  164.0  102000001  000000002  34.0   9.0  1.0   
28640  NaN  NaN  MON02  16165.0  169.0  120001100  05001000x  36.0  10.0  2.0   
30003  NaN  NaN  PIT07  21180.0  159.0  000011400  001000100  36.0  10.0  4.0   
30692  NaN  NaN  PIT07  54274.0  171.0  110022100  000000000  40.0  15.0  2.0   
30809  NaN  NaN  MON02  13986.0  135.0  000000010  20000000x  31.0   5.0  2.0   
31396  NaN  NaN  ATL01  19853.0  192.0  001200013  100000000  35.0  12.0  2.0   
31459  NaN  NaN  MON02  16586.0  175.0  000000000  10001000x  34.0   8.0  1.0   
32852  NaN  NaN  NYC17  22967.0  205.0  000400032  000001001  39.0  12.0  3.0   
33309  NaN  NaN  MON02  20313.0  154.0  000000010  00000160x  28.0   2.0  0.0   
35808  NaN  NaN  MON02  19519.0  144.0  000000100  00000200x  30.0   4.0  1.0   
36689  NaN  NaN  MON02  16429.0  146.0  000000010  30000000x  31.0   8.0  1.0   

       24   25   26   27   28   29   30   31    32   33   34   35   36   37   \
11130  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   6.0  0.0  0.0  0.0  0.0  5.0   
13808  0.0  2.0  3.0  0.0  0.0  0.0  0.0  0.0   8.0  0.0  0.0  1.0  0.0  8.0   
23065  0.0  0.0  0.0  0.0  0.0  0.0  3.0  0.0   6.0  1.0  0.0  0.0  0.0  7.0   
25056  0.0  1.0  6.0  1.0  0.0  0.0  3.0  0.0   4.0  0.0  1.0  1.0  0.0  5.0   
26879  0.0  1.0  4.0  1.0  1.0  0.0  1.0  1.0   4.0  4.0  0.0  0.0  0.0  6.0   
28640  0.0  1.0  4.0  0.0  1.0  1.0  2.0  0.0   3.0  0.0  0.0  1.0  0.0  8.0   
30003  1.0  0.0  6.0  0.0  0.0  0.0  2.0  0.0   7.0  0.0  0.0  1.0  0.0  5.0   
30692  0.0  2.0  6.0  0.0  0.0  0.0  1.0  0.0   4.0  1.0  0.0  1.0  0.0  7.0   
30809  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0   2.0  1.0  0.0  0.0  0.0  4.0   
31396  0.0  2.0  5.0  0.0  1.0  0.0  5.0  0.0   6.0  1.0  1.0  1.0  0.0  7.0   
31459  1.0  0.0  0.0  0.0  0.0  0.0  2.0  0.0   5.0  0.0  0.0  1.0  0.0  9.0   
32852  0.0  0.0  8.0  0.0  0.0  0.0  4.0  1.0  13.0  5.0  1.0  0.0  0.0  7.0   
33309  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0   4.0  0.0  1.0  0.0  0.0  0.0   
35808  0.0  1.0  1.0  0.0  0.0  0.0  3.0  0.0   7.0  3.0  0.0  1.0  0.0  5.0   
36689  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0   7.0  0.0  0.0  4.0  0.0  5.0   

       38   39   40   41   42    43    44   45   46   47   48    49    50   \
11130  3.0  4.0  4.0  0.0  0.0  24.0   4.0  0.0  0.0  1.0  

Now lets go against Cy Young winners 15 - 25 (15 wins, 25 loses) , during his time in montreal, his record was 6-4 (6 wins and 4 loses) with an ERA of 2.74

Against HOF pitchers, his record is 6-8 (6 wins and 8 loses), during his time in montreal he was 4-3 (4 wins and 3 loses) with an ERA of 2.22

In [81]:
mon_hof_wins_df = dennis_martinez_starts[(dennis_martinez_starts[93] == 'martd001') & (dennis_martinez_starts[95].isin(hof_ids))]

In [82]:
mon_hof_loss_df = dennis_martinez_starts[(dennis_martinez_starts[95] == 'martd001') & (dennis_martinez_starts[93].isin(hof_ids))]

In [86]:
mon_hof_total_df = pd.concat([mon_hof_wins_df, mon_hof_loss_df])

In [90]:
mon_hof_total_df[(mon_hof_total_df[3] == 'MON') | (mon_hof_total_df[6] == 'MON')]

0    1    2    3   4    5    6   7    8    9    10   11  12   13   \
31396  19910610    0  Mon  MON  NL   56  ATL  NL   53    7    1   54   N  NaN   
31459  19910615    0  Sat  ATL  NL   58  MON  NL   61    0    2   51   N  NaN   
33309  19920522    0  Fri  ATL  NL   43  MON  NL   38    1    7   51   N  NaN   
35808  19930618    0  Fri  ATL  NL   68  MON  NL   67    1    2   51   N  NaN   
28521  19890926    0  Tue  CHN  NL  158  MON  NL  158    3    2   54   N  NaN   
29525  19900629    0  Fri  ATL  NL   71  MON  NL   75    4    2   54   N  NaN   
37029  19930923    0  Thu  ATL  NL  153  MON  NL  153    6    3   54   N  NaN   

       14   15     16       17     18         19         20    21    22   23   \
31396  NaN  NaN  ATL01  19853.0  192.0  001200013  100000000  35.0  12.0  2.0   
31459  NaN  NaN  MON02  16586.0  175.0  000000000  10001000x  34.0   8.0  1.0   
33309  NaN  NaN  MON02  20313.0  154.0  000000010  00000160x  28.0   2.0  0.0   
35808  NaN  NaN  MON02  19519.0  144.0  000000100  00000200x  30.0   4.0  1.0   
28521  NaN  NaN  MON02  11615.0  175.0  010001010  000002000  33.0   8.0  1.0   
29525  NaN  NaN  MON02  14210.0  172.0  000101200  000100010  32.0   6.0  0.0   
37029  NaN  NaN  MON02  25219.0  152.0  000050010  100001001  34.0   8.0  2.0   

       24   25   26   27   28   29   30   31   32   33   34   35   36   37   \
31396  0.0  2.0  5.0  0.0  1.0  0.0  5.0  0.0  6.0  1.0  1.0  1.0  0.0  7.0   
31459  1.0  0.0  0.0  0.0  0.0  0.0  2.0  0.0  5.0  0.0  0.0  1.0  0.0  9.0   
33309  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0  1.0  0.0  0.0  0.0   
35808  0.0  1.0  1.0  0.0  0.0  0.0  3.0  0.0  7.0  3.0  0.0  1.0  0.0  5.0   
28521  1.0  0.0  2.0  0.0  0.0  0.0  2.0  1.0  7.0  0.0  1.0  1.0  0.0  5.0   
29525  0.0  1.0  4.0  0.0  0.0  0.0  4.0  0.0  9.0  0.0  1.0  0.0  0.0  5.0   
37029  0.0  0.0  5.0  1.0  0.0  1.0  2.0  0.0  4.0  3.0  0.0  1.0  0.0  5.0   

       38   39   40   41   42    43    44   45   46   47   48    49   50   \
31396  3.0  1.0  1.0  0.0  0.0  27.0  11.0  0.0  0.0  1.0  0.0  32.0  7.0   
31459  4.0  2.0  2.0  0.0  0.0  24.0  10.0  0.0  0.0  2.0  0.0  28.0  9.0   
33309  4.0  7.0  7.0  1.0  0.0  24.0  13.0  0.0  0.0  0.0  0.0  32.0  9.0   
35808  2.0  2.0  2.0  0.0  0.0  24.0   7.0  1.0  0.0  2.0  0.0  25.0  4.0   
28521  2.0  2.0  2.0  0.0  0.0  27.0   9.0  1.0  0.0  0.0  0.0  32.0  7.0   
29525  2.0  2.0  2.0  0.0  0.0  27.0  17.0  2.0  0.0  1.0  0.0  32.0  5.0   
37029  2.0  2.0  2.0  0.0  0.0  27.0  16.0  1.0  0.0  1.0  0.0  31.0  7.0   

       51   52   53   54   55   56   57   58   59   60   61   62   63   64   \
31396  2.0  0.0  1.0  1.0  0.0  0.0  0.0  2.0  0.0  5.0  0.0  0.0  1.0  0.0   
31459  1.0  0.0  0.0  2.0  1.0  1.0  0.0  2.0  0.0  9.0  2.0  1.0  0.0  0.0   
33309  3.0  0.0  0.0  7.0  0.0  0.0  0.0  3.0  0.0  0.0  1.0  1.0  0.0  0.0   
35808  2.0  0.0  0.0  2.0  0.0  0.0  0.0  4.0  0.0  8.0  0.0  1.0  1.0  0.0   
28521  1.0  0.0  0.0  2.0  2.0  1.0  0.0  1.0  1.0  7.0  2.0  0.0  0.0  0.0   
29525  1.0  0.0  2.0  2.0  1.0  0.0  0.0  3.0  0.0  6.0  0.0  0.0  1.0  0.0   
37029  1.0  1.0  0.0  3.0  0.0  2.0  0.0  4.0  1.0  5.0  1.0  0.0  1.0  0.0   

       65   66   67   68   69   70    71    72   73   74   75   76        77   \
31396  6.0  2.0  7.0  7.0  1.0  0.0  27.0  11.0  1.0  0.0  2.0  0.0  tatat901   
31459  6.0  1.0  0.0  0.0  1.0  0.0  27.0  12.0  0.0  0.0  1.0  0.0  bonig901   
33309  4.0  1.0  1.0  1.0  0.0  0.0  27.0  11.0  0.0  0.0  0.0  0.0  wintm901   
35808  3.0  2.0  1.0  1.0  0.0  0.0  27.0  11.0  0.0  0.0  1.0  0.0  ripps901   
28521  7.0  1.0  2.0  2.0  0.0  0.0  27.0  13.0  1.0  0.0  2.0  0.0  rennd901   
29525  7.0  2.0  4.0  4.0  0.0  1.0  27.0   9.0  0.0  0.0  0.0  0.0  quicj901   
37029  7.0  2.0  2.0  2.0  0.0  0.0  27.0  14.0  1.0  0.0  1.0  0.0  westj901   

                 78        79             80        81                82   \
31396     Terry Tata  ripps901  Steve Rippley  hohnb901         Bill Hohn   
31459     Greg Bonin  monte9

In [93]:
mon_hof_loss_df[(mon_hof_loss_df[3] == 'MON') | (mon_hof_loss_df[6] == 'MON')]

0    1    2    3   4    5    6   7    8    9    10   11  12   13   \
28521  19890926    0  Tue  CHN  NL  158  MON  NL  158    3    2   54   N  NaN   
29525  19900629    0  Fri  ATL  NL   71  MON  NL   75    4    2   54   N  NaN   
37029  19930923    0  Thu  ATL  NL  153  MON  NL  153    6    3   54   N  NaN   

       14   15     16       17     18         19         20    21   22   23   \
28521  NaN  NaN  MON02  11615.0  175.0  010001010  000002000  33.0  8.0  1.0   
29525  NaN  NaN  MON02  14210.0  172.0  000101200  000100010  32.0  6.0  0.0   
37029  NaN  NaN  MON02  25219.0  152.0  000050010  100001001  34.0  8.0  2.0   

       24   25   26   27   28   29   30   31   32   33   34   35   36   37   \
28521  1.0  0.0  2.0  0.0  0.0  0.0  2.0  1.0  7.0  0.0  1.0  1.0  0.0  5.0   
29525  0.0  1.0  4.0  0.0  0.0  0.0  4.0  0.0  9.0  0.0  1.0  0.0  0.0  5.0   
37029  0.0  0.0  5.0  1.0  0.0  1.0  2.0  0.0  4.0  3.0  0.0  1.0  0.0  5.0   

       38   39   40   41   42    43    44   45   46   47   48    49   50   \
28521  2.0  2.0  2.0  0.0  0.0  27.0   9.0  1.0  0.0  0.0  0.0  32.0  7.0   
29525  2.0  2.0  2.0  0.0  0.0  27.0  17.0  2.0  0.0  1.0  0.0  32.0  5.0   
37029  2.0  2.0  2.0  0.0  0.0  27.0  16.0  1.0  0.0  1.0  0.0  31.0  7.0   

       51   52   53   54   55   56   57   58   59   60   61   62   63   64   \
28521  1.0  0.0  0.0  2.0  2.0  1.0  0.0  1.0  1.0  7.0  2.0  0.0  0.0  0.0   
29525  1.0  0.0  2.0  2.0  1.0  0.0  0.0  3.0  0.0  6.0  0.0  0.0  1.0  0.0   
37029  1.0  1.0  0.0  3.0  0.0  2.0  0.0  4.0  1.0  5.0  1.0  0.0  1.0  0.0   

       65   66   67   68   69   70    71    72   73   74   75   76        77   \
28521  7.0  1.0  2.0  2.0  0.0  0.0  27.0  13.0  1.0  0.0  2.0  0.0  rennd901   
29525  7.0  2.0  4.0  4.0  0.0  1.0  27.0   9.0  0.0  0.0  0.0  0.0  quicj901   
37029  7.0  2.0  2.0  2.0  0.0  0.0  27.0  14.0  1.0  0.0  1.0  0.0  westj901   

                 78        79             80        81                82   \
28521  Dutch Rennert  rungp901     Paul Runge  brocf901  Fred Brocklander   
29525      Jim Quick  rennd901  Dutch Rennert  tatat901        Terry Tata   
37029       Joe West  vanol901  Larry Vanover  marsr901       Randy Marsh   

            83          84   85      86   87      88        89          90   \
28521  engeb901   Bob Engel  NaN  (none)  NaN  (none)  zimmd101  Don Zimmer   
29525  bonig901  Greg Bonin  NaN  (none)  NaN  (none)  cox-b103   Bobby Cox   
37029  rapue901  Ed Rapuano  NaN  (none)  NaN  (none)  cox-b103   Bobby Cox   

            91            92        93           94        95   \
28521  rodgb102  Buck Rodgers  maddg002  Greg Maddux  martd001   
29525  rodgb102  Buck Rodgers  glavt001  Tom Glavine  martd001   
37029  alouf101   Felipe Alou  maddg002  Greg Maddux  martd001   

                   96        97              98        99             100  \
28521  Dennis Martinez  willm002  Mitch Williams       NaN         (none)   
29525  Dennis Martinez  heskj001     Joe Hesketh  justd001  David Justice   
37029  Dennis Martinez       NaN          (none)       NaN         (none)   

            101          102       103              104       105  \
28521  maddg002  Greg Maddux  martd001  Dennis Martinez  wynnm001   
29525  glavt001  Tom Glavine  martd001  Dennis Martinez  mcdoo001   
37029  maddg002  Greg Maddux  martd001  Dennis Martinez  nixoo001   

                   106  107       108            109  110       111  \
28521    Marvell Wynne  8.0  sandr001  Ryne Sandberg  4.0  smitd003   
29525  Oddibe McDowell  8.0  treaj001  Jeff Treadway  4.0  gantr001   
37029       Otis Nixon  8.0  blauj001   Jeff Blauser  6.0  gantr001   

                112  113       114           115  116       117  \
28521  Dwight Smith  7.0  gracm001    Mark Grace  3.0  dawsa001   
29525      Ron Gant  7.0  presj001   Jim Presley  5.0  justd001   
37029      Ron Gant  7.0  mcgrf001  Fred McGriff  3.0  justd001   

                 118  119       120              121  122       123

In [94]:
mon_hof_wins_df[(mon_hof_wins_df[3] == 'MON') | (mon_hof_wins_df[6] == 'MON')]

0    1    2    3   4    5    6   7    8    9    10   11  12   13   \
31396  19910610    0  Mon  MON  NL   56  ATL  NL   53    7    1   54   N  NaN   
31459  19910615    0  Sat  ATL  NL   58  MON  NL   61    0    2   51   N  NaN   
33309  19920522    0  Fri  ATL  NL   43  MON  NL   38    1    7   51   N  NaN   
35808  19930618    0  Fri  ATL  NL   68  MON  NL   67    1    2   51   N  NaN   

       14   15     16       17     18         19         20    21    22   23   \
31396  NaN  NaN  ATL01  19853.0  192.0  001200013  100000000  35.0  12.0  2.0   
31459  NaN  NaN  MON02  16586.0  175.0  000000000  10001000x  34.0   8.0  1.0   
33309  NaN  NaN  MON02  20313.0  154.0  000000010  00000160x  28.0   2.0  0.0   
35808  NaN  NaN  MON02  19519.0  144.0  000000100  00000200x  30.0   4.0  1.0   

       24   25   26   27   28   29   30   31   32   33   34   35   36   37   \
31396  0.0  2.0  5.0  0.0  1.0  0.0  5.0  0.0  6.0  1.0  1.0  1.0  0.0  7.0   
31459  1.0  0.0  0.0  0.0  0.0  0.0  2.0  0.0  5.0  0.0  0.0  1.0  0.0  9.0   
33309  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0  1.0  0.0  0.0  0.0   
35808  0.0  1.0  1.0  0.0  0.0  0.0  3.0  0.0  7.0  3.0  0.0  1.0  0.0  5.0   

       38   39   40   41   42    43    44   45   46   47   48    49   50   \
31396  3.0  1.0  1.0  0.0  0.0  27.0  11.0  0.0  0.0  1.0  0.0  32.0  7.0   
31459  4.0  2.0  2.0  0.0  0.0  24.0  10.0  0.0  0.0  2.0  0.0  28.0  9.0   
33309  4.0  7.0  7.0  1.0  0.0  24.0  13.0  0.0  0.0  0.0  0.0  32.0  9.0   
35808  2.0  2.0  2.0  0.0  0.0  24.0   7.0  1.0  0.0  2.0  0.0  25.0  4.0   

       51   52   53   54   55   56   57   58   59   60   61   62   63   64   \
31396  2.0  0.0  1.0  1.0  0.0  0.0  0.0  2.0  0.0  5.0  0.0  0.0  1.0  0.0   
31459  1.0  0.0  0.0  2.0  1.0  1.0  0.0  2.0  0.0  9.0  2.0  1.0  0.0  0.0   
33309  3.0  0.0  0.0  7.0  0.0  0.0  0.0  3.0  0.0  0.0  1.0  1.0  0.0  0.0   
35808  2.0  0.0  0.0  2.0  0.0  0.0  0.0  4.0  0.0  8.0  0.0  1.0  1.0  0.0   

       65   66   67   68   69   70    71    72   73   74   75   76        77   \
31396  6.0  2.0  7.0  7.0  1.0  0.0  27.0  11.0  1.0  0.0  2.0  0.0  tatat901   
31459  6.0  1.0  0.0  0.0  1.0  0.0  27.0  12.0  0.0  0.0  1.0  0.0  bonig901   
33309  4.0  1.0  1.0  1.0  0.0  0.0  27.0  11.0  0.0  0.0  0.0  0.0  wintm901   
35808  3.0  2.0  1.0  1.0  0.0  0.0  27.0  11.0  0.0  0.0  1.0  0.0  ripps901   

                 78        79             80        81              82   \
31396     Terry Tata  ripps901  Steve Rippley  hohnb901       Bill Hohn   
31459     Greg Bonin  monte901    Ed Montague  rapue901      Ed Rapuano   
33309   Mike Winters  cuzzp901     Phil Cuzzi  monte901     Ed Montague   
35808  Steve Rippley  quicj901      Jim Quick  crawj901  Jerry Crawford   

            83               84   85      86   87      88        89   \
31396  crawj901   Jerry Crawford  NaN  (none)  NaN  (none)  runnt001   
31459  froeb901  Bruce Froemming  NaN  (none)  NaN  (none)  cox-b103   
33309  hallt901      Tom Hallion  NaN  (none)  NaN  (none)  cox-b103   
35808  riekr901      Rich Rieker  NaN  (none)  NaN  (none)  cox-b103   

                90        91            92        93               94   \
31396  Tom Runnells  cox-b103     Bobby Cox  martd001  Dennis Martinez   
31459     Bobby Cox  runnt001  Tom Runnells  martd001  Dennis Martinez   
33309     Bobby Cox  alouf101   Felipe Alou  martd001  Dennis Martinez   
35808     Bobby Cox  alouf101   Felipe Alou  martd001  Dennis Martinez   

            95           96        97              98        99   \
31396  smolj001  John Smoltz  rusks001    Scott Ruskin       NaN   
31459  smolj001  John Smoltz       NaN          (none)  caldi001   
33309  glavt001  Tom Glavine       NaN          (none)  caldi001   
35808  smolj001  John Smoltz  wettj001  John Wetteland  walkl001   

                 100       101              102       103              104  \
31396         (none)  martd001  Dennis Martinez  smolj001      John Smoltz   
31459  Ivan

In [98]:
hof_match_ups = dennis_martinez_starts[((dennis_martinez_starts[101] == 'martd001')  | (dennis_martinez_starts[103] == 'martd001'))
                       & ((dennis_martinez_starts[101].isin(hof_ids)) | (dennis_martinez_starts[103].isin(hof_ids))) ]

In [99]:
hof_match_ups[(hof_match_ups[3] == 'MON') | (hof_match_ups[6] == 'MON')]

0    1    2    3   4    5    6   7    8    9    10   11  12   13   \
22125  19860923    0  Tue  MON  NL  150  CHN  NL  151   10    5   54   D  NaN   
25655  19880726    0  Tue  CHN  NL   99  MON  NL   99    4    8   65   N  NaN   
28521  19890926    0  Tue  CHN  NL  158  MON  NL  158    3    2   54   N  NaN   
29525  19900629    0  Fri  ATL  NL   71  MON  NL   75    4    2   54   N  NaN   
29682  19900714    1  Sat  MON  NL   86  ATL  NL   82    2    3   51   N  NaN   
31396  19910610    0  Mon  MON  NL   56  ATL  NL   53    7    1   54   N  NaN   
31459  19910615    0  Sat  ATL  NL   58  MON  NL   61    0    2   51   N  NaN   
32512  19910913    0  Fri  MON  NL  140  CHN  NL  141    3    2   54   D  NaN   
33309  19920522    0  Fri  ATL  NL   43  MON  NL   38    1    7   51   N  NaN   
35808  19930618    0  Fri  ATL  NL   68  MON  NL   67    1    2   51   N  NaN   
37029  19930923    0  Thu  ATL  NL  153  MON  NL  153    6    3   54   N  NaN   

       14   15     16       17     18           19           20    21    22   \
22125  NaN  NaN  CHI11   4684.0  187.0    220200013    000400001  42.0  18.0   
25655  NaN  NaN  MON02  26029.0  209.0  00000002200  00300000104  43.0  13.0   
28521  NaN  NaN  MON02  11615.0  175.0    010001010    000002000  33.0   8.0   
29525  NaN  NaN  MON02  14210.0  172.0    000101200    000100010  32.0   6.0   
29682  NaN  NaN  ATL01      0.0  158.0    200000000    00000003x  29.0   3.0   
31396  NaN  NaN  ATL01  19853.0  192.0    001200013    100000000  35.0  12.0   
31459  NaN  NaN  MON02  16586.0  175.0    000000000    10001000x  34.0   8.0   
32512  NaN  NaN  CHI11  17668.0  153.0    010010001    000000020  32.0   7.0   
33309  NaN  NaN  MON02  20313.0  154.0    000000010    00000160x  28.0   2.0   
35808  NaN  NaN  MON02  19519.0  144.0    000000100    00000200x  30.0   4.0   
37029  NaN  NaN  MON02  25219.0  152.0    000050010    100001001  34.0   8.0   

       23   24   25   26   27   28   29   30   31    32   33   34   35   36   \
22125  3.0  0.0  1.0  9.0  0.0  0.0  0.0  3.0  2.0   6.0  1.0  2.0  1.0  0.0   
25655  2.0  1.0  0.0  4.0  1.0  1.0  0.0  0.0  0.0   2.0  1.0  0.0  1.0  0.0   
28521  1.0  1.0  0.0  2.0  0.0  0.0  0.0  2.0  1.0   7.0  0.0  1.0  1.0  0.0   
29525  0.0  0.0  1.0  4.0  0.0  0.0  0.0  4.0  0.0   9.0  0.0  1.0  0.0  0.0   
29682  0.0  0.0  0.0  1.0  1.0  0.0  0.0  2.0  0.0  11.0  1.0  1.0  0.0  0.0   
31396  2.0  0.0  2.0  5.0  0.0  1.0  0.0  5.0  0.0   6.0  1.0  1.0  1.0  0.0   
31459  1.0  1.0  0.0  0.0  0.0  0.0  0.0  2.0  0.0   5.0  0.0  0.0  1.0  0.0   
32512  2.0  0.0  0.0  2.0  1.0  1.0  0.0  2.0  0.0   8.0  0.0  0.0  1.0  0.0   
33309  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0   4.0  0.0  1.0  0.0  0.0   
35808  1.0  0.0  1.0  1.0  0.0  0.0  0.0  3.0  0.0   7.0  3.0  0.0  1.0  0.0   
37029  2.0  0.0  0.0  5.0  1.0  0.0  1.0  2.0  0.0   4.0  3.0  0.0  1.0  0.0   

       37   38   39   40   41   42    43    44   45   46   47   48    49   \
22125  8.0  3.0  5.0  5.0  0.0  0.0  27.0  10.0  0.0  1.0  0.0  0.0  38.0   
25655  8.0  4.0  8.0  8.0  1.0  0.0  32.0  14.0  2.0  0.0  0.0  0.0  41.0   
28521  5.0  2.0  2.0  2.0  0.0  0.0  27.0   9.0  1.0  0.0  0.0  0.0  32.0   
29525  5.0  2.0  2.0  2.0  0.0  0.0  27.0  17.0  2.0  0.0  1.0  0.0  32.0   
29682  3.0  3.0  3.0  3.0  0.0  1.0  24.0   7.0  1.0  1.0  0.0  0.0  35.0   
31396  7.0  3.0  1.0  1.0  0.0  0.0  27.0  11.0  0.0  0.0  1.0  0.0  32.0   
31459  9.0  4.0  2.0  2.0  0.0  0.0  24.0  10.0  0.0  0.0  2.0  0.0  28.0   
32512  6.0  2.0  2.0  2.0  0.0  0.0  27.0  14.0  0.0  0.0  0.0  0.0  33.0   
33309  0.0  4.0  7.0  7.0  1.0  0.0  24.0  13.0  0.0  0.0  0.0  0.0  32.0   
35808  5.0  2.0  2.0  2.0  0.0  0.0  24.0   7.0  1.0  0.0  2.0  0.0  25.0   
37029  5.0  2.0  2.0  2.0  0.0  0.0  27.0  16.0  1.0  0.0  1.0  0.0  31.0   

        50   51   52   53   54   55   56   57   58   59    60   61   62   63   \
22125  11.0  1.0  0.0  2.0  5.0  0.0  0.0  0.0  0.0  0.0   9.0  0.0  1.0  0.0   
25655   9.0  1.0  1.0  1.0  7.

In [101]:
#ID -> IP, ER
# 19860923 -> 3.1, 6
# 19880726 -> 7.2, 2
# 19890926 -> 9, 2
# 19900629 -> 7, 4
# 19900714 -> 6, 0
# 19910610 -> 7, 1
# 19910615 -> 9, 0
# 19910913 -> 8, 2
# 19920522 -> 9, 1
# 19930618 -> 8, 1
# 19930923 -> 7, 1

In [103]:
(3.1 + 7.2+9 + 7 +7 +9+8+9+8+7 + 6)
# 81 IP

80.3

In [104]:
(6+2+2+4+1+0+2+1+1+1 + 0)

20

In [105]:
# ERA
(20/81) * 9

2.2222222222222223